syntax = "proto3";

package KNIRVCHAIN;

option go_package = "KNIRVCHAIN/internal/protocol/proto";

import "google/protobuf/timestamp.proto";

message TransactionProto {
  string from = 1;
  string to = 2;
  uint64 value = 3;
  bytes data = 4;
  google.protobuf.Timestamp timestamp = 5;
  uint64 fee = 6;
  string type = 7;
  bytes signature = 8;
  bytes public_key = 9;
}

message BlockProto {
  uint64 block_number = 1;
  bytes prev_hash = 2;
  google.protobuf.Timestamp timestamp = 3;
  int32 nonce = 4;
  repeated TransactionProto transactions = 5;
  string proposer_address = 6;
}

// LLMRootingData contains the core metadata for an LLM model rooting transaction
message LLMRootingDataProto {
  string model_name = 1;
  string model_owner = 2;
  string api_endpoint = 3;
  string metadata_cid = 4;
  string cmu = 5;
}