// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.7
// source: mcp_context.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for InteractionType
type InteractionTypeProto int32

const (
	InteractionTypeProto_INTERACTION_TYPE_PROTO_UNSPECIFIED                InteractionTypeProto = 0
	InteractionTypeProto_INTERACTION_TYPE_PROTO_TOOL_INVOCATION            InteractionTypeProto = 1
	InteractionTypeProto_INTERACTION_TYPE_PROTO_PROMPT_USAGE               InteractionTypeProto = 2
	InteractionTypeProto_INTERACTION_TYPE_PROTO_RESOURCE_ACCESS            InteractionTypeProto = 3
	InteractionTypeProto_INTERACTION_TYPE_PROTO_PLUGIN_EXECUTION           InteractionTypeProto = 4
	InteractionTypeProto_INTERACTION_TYPE_PROTO_SAMPLING_REQUEST_SENT      InteractionTypeProto = 5
	InteractionTypeProto_INTERACTION_TYPE_PROTO_SAMPLING_RESPONSE_RECEIVED InteractionTypeProto = 6
	InteractionTypeProto_INTERACTION_TYPE_PROTO_MEMORY_WRITE               InteractionTypeProto = 7
	InteractionTypeProto_INTERACTION_TYPE_PROTO_CAPABILITY_REGISTRATION    InteractionTypeProto = 8
)

// Enum value maps for InteractionTypeProto.
var (
	InteractionTypeProto_name = map[int32]string{
		0: "INTERACTION_TYPE_PROTO_UNSPECIFIED",
		1: "INTERACTION_TYPE_PROTO_TOOL_INVOCATION",
		2: "INTERACTION_TYPE_PROTO_PROMPT_USAGE",
		3: "INTERACTION_TYPE_PROTO_RESOURCE_ACCESS",
		4: "INTERACTION_TYPE_PROTO_PLUGIN_EXECUTION",
		5: "INTERACTION_TYPE_PROTO_SAMPLING_REQUEST_SENT",
		6: "INTERACTION_TYPE_PROTO_SAMPLING_RESPONSE_RECEIVED",
		7: "INTERACTION_TYPE_PROTO_MEMORY_WRITE",
		8: "INTERACTION_TYPE_PROTO_CAPABILITY_REGISTRATION",
	}
	InteractionTypeProto_value = map[string]int32{
		"INTERACTION_TYPE_PROTO_UNSPECIFIED":                0,
		"INTERACTION_TYPE_PROTO_TOOL_INVOCATION":            1,
		"INTERACTION_TYPE_PROTO_PROMPT_USAGE":               2,
		"INTERACTION_TYPE_PROTO_RESOURCE_ACCESS":            3,
		"INTERACTION_TYPE_PROTO_PLUGIN_EXECUTION":           4,
		"INTERACTION_TYPE_PROTO_SAMPLING_REQUEST_SENT":      5,
		"INTERACTION_TYPE_PROTO_SAMPLING_RESPONSE_RECEIVED": 6,
		"INTERACTION_TYPE_PROTO_MEMORY_WRITE":               7,
		"INTERACTION_TYPE_PROTO_CAPABILITY_REGISTRATION":    8,
	}
)

func (x InteractionTypeProto) Enum() *InteractionTypeProto {
	p := new(InteractionTypeProto)
	*p = x
	return p
}

func (x InteractionTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractionTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_context_proto_enumTypes[0].Descriptor()
}

func (InteractionTypeProto) Type() protoreflect.EnumType {
	return &file_mcp_context_proto_enumTypes[0]
}

func (x InteractionTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractionTypeProto.Descriptor instead.
func (InteractionTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_mcp_context_proto_rawDescGZIP(), []int{0}
}

// ContextRecordProto corresponds to ContextRecord
type ContextRecordProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CapabilityId    string                 `protobuf:"bytes,2,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	InteractionType InteractionTypeProto   `protobuf:"varint,3,opt,name=interaction_type,json=interactionType,proto3,enum=KNIRVCHAIN.InteractionTypeProto" json:"interaction_type,omitempty"`
	Initiator       string                 `protobuf:"bytes,4,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	InputHash       string                 `protobuf:"bytes,6,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	OutputHash      string                 `protobuf:"bytes,7,opt,name=output_hash,json=outputHash,proto3" json:"output_hash,omitempty"`
	Details         *structpb.Struct       `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`     // Maps to map[string]interface{}
	Signature       []byte                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"` // Keep as bytes for signature
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContextRecordProto) Reset() {
	*x = ContextRecordProto{}
	mi := &file_mcp_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRecordProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRecordProto) ProtoMessage() {}

func (x *ContextRecordProto) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRecordProto.ProtoReflect.Descriptor instead.
func (*ContextRecordProto) Descriptor() ([]byte, []int) {
	return file_mcp_context_proto_rawDescGZIP(), []int{0}
}

func (x *ContextRecordProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContextRecordProto) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ContextRecordProto) GetInteractionType() InteractionTypeProto {
	if x != nil {
		return x.InteractionType
	}
	return InteractionTypeProto_INTERACTION_TYPE_PROTO_UNSPECIFIED
}

func (x *ContextRecordProto) GetInitiator() string {
	if x != nil {
		return x.Initiator
	}
	return ""
}

func (x *ContextRecordProto) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ContextRecordProto) GetInputHash() string {
	if x != nil {
		return x.InputHash
	}
	return ""
}

func (x *ContextRecordProto) GetOutputHash() string {
	if x != nil {
		return x.OutputHash
	}
	return ""
}

func (x *ContextRecordProto) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ContextRecordProto) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// For transaction data
type MCPInvokeCapabilityDataProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextRecord *ContextRecordProto    `protobuf:"bytes,1,opt,name=context_record,json=contextRecord,proto3" json:"context_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPInvokeCapabilityDataProto) Reset() {
	*x = MCPInvokeCapabilityDataProto{}
	mi := &file_mcp_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPInvokeCapabilityDataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPInvokeCapabilityDataProto) ProtoMessage() {}

func (x *MCPInvokeCapabilityDataProto) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPInvokeCapabilityDataProto.ProtoReflect.Descriptor instead.
func (*MCPInvokeCapabilityDataProto) Descriptor() ([]byte, []int) {
	return file_mcp_context_proto_rawDescGZIP(), []int{1}
}

func (x *MCPInvokeCapabilityDataProto) GetContextRecord() *ContextRecordProto {
	if x != nil {
		return x.ContextRecord
	}
	return nil
}

var File_mcp_context_proto protoreflect.FileDescriptor

const file_mcp_context_proto_rawDesc = "" +
	"\n" +
	"\x11mcp_context.proto\x12\n" +
	"KNIRVCHAIN\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x02\n" +
	"\x12ContextRecordProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcapability_id\x18\x02 \x01(\tR\fcapabilityId\x12K\n" +
	"\x10interaction_type\x18\x03 \x01(\x0e2 .KNIRVCHAIN.InteractionTypeProtoR\x0finteractionType\x12\x1c\n" +
	"\tinitiator\x18\x04 \x01(\tR\tinitiator\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"input_hash\x18\x06 \x01(\tR\tinputHash\x12\x1f\n" +
	"\voutput_hash\x18\a \x01(\tR\n" +
	"outputHash\x121\n" +
	"\adetails\x18\b \x01(\v2\x17.google.protobuf.StructR\adetails\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\"e\n" +
	"\x1cMCPInvokeCapabilityDataProto\x12E\n" +
	"\x0econtext_record\x18\x01 \x01(\v2\x1e.KNIRVCHAIN.ContextRecordProtoR\rcontextRecord*\xb2\x03\n" +
	"\x14InteractionTypeProto\x12&\n" +
	"\"INTERACTION_TYPE_PROTO_UNSPECIFIED\x10\x00\x12*\n" +
	"&INTERACTION_TYPE_PROTO_TOOL_INVOCATION\x10\x01\x12'\n" +
	"#INTERACTION_TYPE_PROTO_PROMPT_USAGE\x10\x02\x12*\n" +
	"&INTERACTION_TYPE_PROTO_RESOURCE_ACCESS\x10\x03\x12+\n" +
	"'INTERACTION_TYPE_PROTO_PLUGIN_EXECUTION\x10\x04\x120\n" +
	",INTERACTION_TYPE_PROTO_SAMPLING_REQUEST_SENT\x10\x05\x125\n" +
	"1INTERACTION_TYPE_PROTO_SAMPLING_RESPONSE_RECEIVED\x10\x06\x12'\n" +
	"#INTERACTION_TYPE_PROTO_MEMORY_WRITE\x10\a\x122\n" +
	".INTERACTION_TYPE_PROTO_CAPABILITY_REGISTRATION\x10\bB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_mcp_context_proto_rawDescOnce sync.Once
	file_mcp_context_proto_rawDescData []byte
)

func file_mcp_context_proto_rawDescGZIP() []byte {
	file_mcp_context_proto_rawDescOnce.Do(func() {
		file_mcp_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_context_proto_rawDesc), len(file_mcp_context_proto_rawDesc)))
	})
	return file_mcp_context_proto_rawDescData
}

var file_mcp_context_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_context_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcp_context_proto_goTypes = []any{
	(InteractionTypeProto)(0),            // 0: KNIRVCHAIN.InteractionTypeProto
	(*ContextRecordProto)(nil),           // 1: KNIRVCHAIN.ContextRecordProto
	(*MCPInvokeCapabilityDataProto)(nil), // 2: KNIRVCHAIN.MCPInvokeCapabilityDataProto
	(*timestamppb.Timestamp)(nil),        // 3: google.protobuf.Timestamp
	(*structpb.Struct)(nil),              // 4: google.protobuf.Struct
}
var file_mcp_context_proto_depIdxs = []int32{
	0, // 0: KNIRVCHAIN.ContextRecordProto.interaction_type:type_name -> KNIRVCHAIN.InteractionTypeProto
	3, // 1: KNIRVCHAIN.ContextRecordProto.timestamp:type_name -> google.protobuf.Timestamp
	4, // 2: KNIRVCHAIN.ContextRecordProto.details:type_name -> google.protobuf.Struct
	1, // 3: KNIRVCHAIN.MCPInvokeCapabilityDataProto.context_record:type_name -> KNIRVCHAIN.ContextRecordProto
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mcp_context_proto_init() }
func file_mcp_context_proto_init() {
	if File_mcp_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_context_proto_rawDesc), len(file_mcp_context_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_context_proto_goTypes,
		DependencyIndexes: file_mcp_context_proto_depIdxs,
		EnumInfos:         file_mcp_context_proto_enumTypes,
		MessageInfos:      file_mcp_context_proto_msgTypes,
	}.Build()
	File_mcp_context_proto = out.File
	file_mcp_context_proto_goTypes = nil
	file_mcp_context_proto_depIdxs = nil
}
