import { execFileSync } from "node:child_process";
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const output = resolve(root, "wasm");
const modulesOutput = resolve(root, "modules");
const coreAssets = resolve(root, "../core/wasm-modules/assets");
rmSync(output, { recursive: true, force: true });
mkdirSync(output, { recursive: true });

execFileSync("wasm-pack", ["build", "wasm-core", "--target", "web", "--release", "--out-dir", "../wasm", "--out-name", "knirv_sdk_core"], { cwd: root, stdio: "inherit" });
// wasm-pack writes `wasm/.gitignore` containing `*`; npm honors it even when
// package.json explicitly includes wasm/, so remove this generated file.
rmSync(resolve(output, ".gitignore"), { force: true });

const binary = readFileSync(resolve(output, "knirv_sdk_core_bg.wasm"));
writeFileSync(resolve(output, "inlined_base64.js"), `// Generated by scripts/build.mjs; do not edit.\nconst base64 = "${binary.toString("base64")}";\nexport const inlinedWasmBytes = Uint8Array.from(atob(base64), char => char.charCodeAt(0));\n`);
writeFileSync(resolve(output, "inlined_base64.d.ts"), "export declare const inlinedWasmBytes: Uint8Array;\n");

const moduleDetails = {
  "cognitive-shell": { module_kind: "cognitive", capabilities: ["cognitive.process"] },
  "controller-relay": { module_kind: "relay", capabilities: ["relay.envelope"] },
  "crypto-core": { module_kind: "crypto", capabilities: ["crypto.policy"] },
  "dve-verifier": { module_kind: "verifier", capabilities: ["dve.verify"] }
};
rmSync(modulesOutput, { recursive: true, force: true });
mkdirSync(modulesOutput, { recursive: true });
const modules = Object.entries(moduleDetails).map(([id, details]) => {
  const filename = `${id}.wasm`;
  const source = resolve(coreAssets, filename);
  const bytes = readFileSync(source);
  copyFileSync(source, resolve(modulesOutput, filename));
  return { id, artifact_version: "1.0.0", abi_version: 1, byte_length: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex"), ...details };
});
writeFileSync(resolve(modulesOutput, "manifest.json"), `${JSON.stringify({ version: 1, modules }, null, 2)}\n`);
writeFileSync(resolve(modulesOutput, "manifest.js"), `// Generated by scripts/build.mjs; do not edit.\nexport const wasmModulesManifest = ${JSON.stringify({ version: 1, modules })};\n`);
writeFileSync(resolve(modulesOutput, "manifest.d.ts"), "import type { WasmModuleManifest } from '../modules.js';\nexport declare const wasmModulesManifest: WasmModuleManifest;\n");
