// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.7
// source: internal/proto/hasher/v1/hasher.proto

package hasherv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ComputeHashRequest contains data for single hash computation
type ComputeHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Data to hash (arbitrary bytes)
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ComputeHashRequest) Reset() {
	*x = ComputeHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeHashRequest) ProtoMessage() {}

func (x *ComputeHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeHashRequest.ProtoReflect.Descriptor instead.
func (*ComputeHashRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeHashRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ComputeHashResponse contains the computed hash and latency info
type ComputeHashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Computed SHA-256 hash (32 bytes)
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Operation latency in microseconds
	LatencyUs uint64 `protobuf:"varint,2,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"`
}

func (x *ComputeHashResponse) Reset() {
	*x = ComputeHashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeHashResponse) ProtoMessage() {}

func (x *ComputeHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeHashResponse.ProtoReflect.Descriptor instead.
func (*ComputeHashResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeHashResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ComputeHashResponse) GetLatencyUs() uint64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

// ComputeBatchRequest contains multiple data items to hash
type ComputeBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Array of data items to hash
	Data [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// Maximum batch size (optional, defaults to 256)
	// Server will process in optimal hardware batches
	MaxBatchSize uint32 `protobuf:"varint,2,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`
}

func (x *ComputeBatchRequest) Reset() {
	*x = ComputeBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeBatchRequest) ProtoMessage() {}

func (x *ComputeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeBatchRequest.ProtoReflect.Descriptor instead.
func (*ComputeBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{2}
}

func (x *ComputeBatchRequest) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ComputeBatchRequest) GetMaxBatchSize() uint32 {
	if x != nil {
		return x.MaxBatchSize
	}
	return 0
}

// ComputeBatchResponse contains all computed hashes
type ComputeBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Array of computed hashes (same order as input)
	Hashes [][]byte `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	// Total operation latency in microseconds
	TotalLatencyUs uint64 `protobuf:"varint,2,opt,name=total_latency_us,json=totalLatencyUs,proto3" json:"total_latency_us,omitempty"`
	// Number of hashes successfully processed
	ProcessedCount uint32 `protobuf:"varint,3,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
}

func (x *ComputeBatchResponse) Reset() {
	*x = ComputeBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeBatchResponse) ProtoMessage() {}

func (x *ComputeBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeBatchResponse.ProtoReflect.Descriptor instead.
func (*ComputeBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{3}
}

func (x *ComputeBatchResponse) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *ComputeBatchResponse) GetTotalLatencyUs() uint64 {
	if x != nil {
		return x.TotalLatencyUs
	}
	return 0
}

func (x *ComputeBatchResponse) GetProcessedCount() uint32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

// StreamComputeRequest is sent by client in streaming mode
type StreamComputeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Data to hash
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Client-provided request ID for correlation
	RequestId uint64 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *StreamComputeRequest) Reset() {
	*x = StreamComputeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamComputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamComputeRequest) ProtoMessage() {}

func (x *StreamComputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamComputeRequest.ProtoReflect.Descriptor instead.
func (*StreamComputeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{4}
}

func (x *StreamComputeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamComputeRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// StreamComputeResponse is returned by server in streaming mode
type StreamComputeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Computed hash
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Request ID from the original request
	RequestId uint64 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Operation latency in microseconds
	LatencyUs uint64 `protobuf:"varint,3,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"`
}

func (x *StreamComputeResponse) Reset() {
	*x = StreamComputeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamComputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamComputeResponse) ProtoMessage() {}

func (x *StreamComputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamComputeResponse.ProtoReflect.Descriptor instead.
func (*StreamComputeResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{5}
}

func (x *StreamComputeResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *StreamComputeResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *StreamComputeResponse) GetLatencyUs() uint64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

// GetMetricsRequest requests performance metrics
type GetMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{6}
}

// GetMetricsResponse contains aggregated performance metrics
type GetMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Total number of hash requests processed
	TotalRequests uint64 `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	// Total bytes processed across all requests
	TotalBytesProcessed uint64 `protobuf:"varint,2,opt,name=total_bytes_processed,json=totalBytesProcessed,proto3" json:"total_bytes_processed,omitempty"`
	// Average latency in microseconds
	AverageLatencyUs uint64 `protobuf:"varint,3,opt,name=average_latency_us,json=averageLatencyUs,proto3" json:"average_latency_us,omitempty"`
	// Peak latency in microseconds
	PeakLatencyUs uint64 `protobuf:"varint,4,opt,name=peak_latency_us,json=peakLatencyUs,proto3" json:"peak_latency_us,omitempty"`
	// Total number of errors encountered
	TotalErrors uint64 `protobuf:"varint,5,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	// Cache hit count (reserved for future use)
	CacheHits uint64 `protobuf:"varint,6,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	// Cache miss count (reserved for future use)
	CacheMisses uint64 `protobuf:"varint,7,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	// Device-specific statistics
	DeviceStats map[string]uint64 `protobuf:"bytes,8,rep,name=device_stats,json=deviceStats,proto3" json:"device_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{7}
}

func (x *GetMetricsResponse) GetTotalRequests() uint64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalBytesProcessed() uint64 {
	if x != nil {
		return x.TotalBytesProcessed
	}
	return 0
}

func (x *GetMetricsResponse) GetAverageLatencyUs() uint64 {
	if x != nil {
		return x.AverageLatencyUs
	}
	return 0
}

func (x *GetMetricsResponse) GetPeakLatencyUs() uint64 {
	if x != nil {
		return x.PeakLatencyUs
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalErrors() uint64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

func (x *GetMetricsResponse) GetCacheHits() uint64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *GetMetricsResponse) GetCacheMisses() uint64 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

func (x *GetMetricsResponse) GetDeviceStats() map[string]uint64 {
	if x != nil {
		return x.DeviceStats
	}
	return nil
}

// GetDeviceInfoRequest requests device information
type GetDeviceInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDeviceInfoRequest) Reset() {
	*x = GetDeviceInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceInfoRequest) ProtoMessage() {}

func (x *GetDeviceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{8}
}

// GetDeviceInfoResponse contains ASIC device information
type GetDeviceInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Device file path (e.g., /dev/bitmain-asic)
	DevicePath string `protobuf:"bytes,1,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	// Number of chips in the ASIC
	ChipCount uint32 `protobuf:"varint,2,opt,name=chip_count,json=chipCount,proto3" json:"chip_count,omitempty"`
	// Firmware version string
	FirmwareVersion string `protobuf:"bytes,3,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	// Whether device is operational
	IsOperational bool `protobuf:"varint,4,opt,name=is_operational,json=isOperational,proto3" json:"is_operational,omitempty"`
	// Server uptime in seconds
	UptimeSeconds uint64 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
}

func (x *GetDeviceInfoResponse) Reset() {
	*x = GetDeviceInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceInfoResponse) ProtoMessage() {}

func (x *GetDeviceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{9}
}

func (x *GetDeviceInfoResponse) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *GetDeviceInfoResponse) GetChipCount() uint32 {
	if x != nil {
		return x.ChipCount
	}
	return 0
}

func (x *GetDeviceInfoResponse) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *GetDeviceInfoResponse) GetIsOperational() bool {
	if x != nil {
		return x.IsOperational
	}
	return false
}

func (x *GetDeviceInfoResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// MineWorkRequest contains data for mining a nonce
type MineWorkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 80-byte Bitcoin-style block header
	Header []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Starting nonce value for search
	NonceStart uint32 `protobuf:"varint,2,opt,name=nonce_start,json=nonceStart,proto3" json:"nonce_start,omitempty"`
	// Ending nonce value for search
	NonceEnd uint32 `protobuf:"varint,3,opt,name=nonce_end,json=nonceEnd,proto3" json:"nonce_end,omitempty"`
}

func (x *MineWorkRequest) Reset() {
	*x = MineWorkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MineWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MineWorkRequest) ProtoMessage() {}

func (x *MineWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MineWorkRequest.ProtoReflect.Descriptor instead.
func (*MineWorkRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{10}
}

func (x *MineWorkRequest) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MineWorkRequest) GetNonceStart() uint32 {
	if x != nil {
		return x.NonceStart
	}
	return 0
}

func (x *MineWorkRequest) GetNonceEnd() uint32 {
	if x != nil {
		return x.NonceEnd
	}
	return 0
}

// MineWorkResponse contains the found nonce
type MineWorkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The first valid nonce found
	Nonce uint32 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Operation latency in microseconds
	LatencyUs uint64 `protobuf:"varint,2,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"`
}

func (x *MineWorkResponse) Reset() {
	*x = MineWorkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MineWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MineWorkResponse) ProtoMessage() {}

func (x *MineWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hasher_v1_hasher_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MineWorkResponse.ProtoReflect.Descriptor instead.
func (*MineWorkResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP(), []int{11}
}

func (x *MineWorkResponse) GetNonce() uint32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *MineWorkResponse) GetLatencyUs() uint64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

var File_internal_proto_hasher_v1_hasher_proto protoreflect.FileDescriptor

var file_internal_proto_hasher_v1_hasher_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x22, 0x28, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x48, 0x61, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x13,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x6e,
	0x63, 0x79, 0x5f, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6c, 0x61, 0x74,
	0x65, 0x6e, 0x63, 0x79, 0x55, 0x73, 0x22, 0x4f, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79,
	0x55, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x49, 0x0a, 0x14, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x69, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x55,
	0x73, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xbd, 0x03, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x15, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4c, 0x61, 0x74,
	0x65, 0x6e, 0x63, 0x79, 0x55, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x65, 0x61, 0x6b, 0x5f, 0x6c,
	0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0d, 0x70, 0x65, 0x61, 0x6b, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x55, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x68, 0x69, 0x74, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x61, 0x63, 0x68, 0x65, 0x48, 0x69, 0x74, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x4d, 0x69, 0x73,
	0x73, 0x65, 0x73, 0x12, 0x51, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x68, 0x61, 0x73, 0x68,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x1a, 0x3e, 0x0a, 0x10, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd0,
	0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x69,
	0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63,
	0x68, 0x69, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x66, 0x69, 0x72, 0x6d,
	0x77, 0x61, 0x72, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x66, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x75, 0x70,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0d, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x22, 0x67, 0x0a, 0x0f, 0x4d, 0x69, 0x6e, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x45, 0x6e, 0x64, 0x22, 0x47, 0x0a, 0x10, 0x4d, 0x69,
	0x6e, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x55, 0x73, 0x32, 0xea, 0x03, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x1e, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x49, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x1c, 0x2e, 0x68, 0x61, 0x73,
	0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x68, 0x61, 0x73, 0x68,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x4d,
	0x69, 0x6e, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x1a, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x69, 0x6e, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x69, 0x6e, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x21, 0x5a, 0x1f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x68, 0x61, 0x73, 0x68, 0x65,
	0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_hasher_v1_hasher_proto_rawDescOnce sync.Once
	file_internal_proto_hasher_v1_hasher_proto_rawDescData = file_internal_proto_hasher_v1_hasher_proto_rawDesc
)

func file_internal_proto_hasher_v1_hasher_proto_rawDescGZIP() []byte {
	file_internal_proto_hasher_v1_hasher_proto_rawDescOnce.Do(func() {
		file_internal_proto_hasher_v1_hasher_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_hasher_v1_hasher_proto_rawDescData)
	})
	return file_internal_proto_hasher_v1_hasher_proto_rawDescData
}

var file_internal_proto_hasher_v1_hasher_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_proto_hasher_v1_hasher_proto_goTypes = []interface{}{
	(*ComputeHashRequest)(nil),    // 0: hasher.v1.ComputeHashRequest
	(*ComputeHashResponse)(nil),   // 1: hasher.v1.ComputeHashResponse
	(*ComputeBatchRequest)(nil),   // 2: hasher.v1.ComputeBatchRequest
	(*ComputeBatchResponse)(nil),  // 3: hasher.v1.ComputeBatchResponse
	(*StreamComputeRequest)(nil),  // 4: hasher.v1.StreamComputeRequest
	(*StreamComputeResponse)(nil), // 5: hasher.v1.StreamComputeResponse
	(*GetMetricsRequest)(nil),     // 6: hasher.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),    // 7: hasher.v1.GetMetricsResponse
	(*GetDeviceInfoRequest)(nil),  // 8: hasher.v1.GetDeviceInfoRequest
	(*GetDeviceInfoResponse)(nil), // 9: hasher.v1.GetDeviceInfoResponse
	(*MineWorkRequest)(nil),       // 10: hasher.v1.MineWorkRequest
	(*MineWorkResponse)(nil),      // 11: hasher.v1.MineWorkResponse
	nil,                           // 12: hasher.v1.GetMetricsResponse.DeviceStatsEntry
}
var file_internal_proto_hasher_v1_hasher_proto_depIdxs = []int32{
	12, // 0: hasher.v1.GetMetricsResponse.device_stats:type_name -> hasher.v1.GetMetricsResponse.DeviceStatsEntry
	0,  // 1: hasher.v1.hasherService.ComputeHash:input_type -> hasher.v1.ComputeHashRequest
	2,  // 2: hasher.v1.hasherService.ComputeBatch:input_type -> hasher.v1.ComputeBatchRequest
	4,  // 3: hasher.v1.hasherService.StreamCompute:input_type -> hasher.v1.StreamComputeRequest
	6,  // 4: hasher.v1.hasherService.GetMetrics:input_type -> hasher.v1.GetMetricsRequest
	8,  // 5: hasher.v1.hasherService.GetDeviceInfo:input_type -> hasher.v1.GetDeviceInfoRequest
	10, // 6: hasher.v1.hasherService.MineWork:input_type -> hasher.v1.MineWorkRequest
	1,  // 7: hasher.v1.hasherService.ComputeHash:output_type -> hasher.v1.ComputeHashResponse
	3,  // 8: hasher.v1.hasherService.ComputeBatch:output_type -> hasher.v1.ComputeBatchResponse
	5,  // 9: hasher.v1.hasherService.StreamCompute:output_type -> hasher.v1.StreamComputeResponse
	7,  // 10: hasher.v1.hasherService.GetMetrics:output_type -> hasher.v1.GetMetricsResponse
	9,  // 11: hasher.v1.hasherService.GetDeviceInfo:output_type -> hasher.v1.GetDeviceInfoResponse
	11, // 12: hasher.v1.hasherService.MineWork:output_type -> hasher.v1.MineWorkResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_hasher_v1_hasher_proto_init() }
func file_internal_proto_hasher_v1_hasher_proto_init() {
	if File_internal_proto_hasher_v1_hasher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComputeHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComputeHashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComputeBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComputeBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamComputeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamComputeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MineWorkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hasher_v1_hasher_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MineWorkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_hasher_v1_hasher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_hasher_v1_hasher_proto_goTypes,
		DependencyIndexes: file_internal_proto_hasher_v1_hasher_proto_depIdxs,
		MessageInfos:      file_internal_proto_hasher_v1_hasher_proto_msgTypes,
	}.Build()
	File_internal_proto_hasher_v1_hasher_proto = out.File
	file_internal_proto_hasher_v1_hasher_proto_rawDesc = nil
	file_internal_proto_hasher_v1_hasher_proto_goTypes = nil
	file_internal_proto_hasher_v1_hasher_proto_depIdxs = nil
}
