// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.7
// source: internal/proto/pixie/v1/pixie.proto

package pixiev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PixieServiceClient is the client API for PixieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PixieServiceClient interface {
	// ComputeHash computes a single SHA-256 hash
	ComputeHash(ctx context.Context, in *ComputeHashRequest, opts ...grpc.CallOption) (*ComputeHashResponse, error)
	// ComputeBatch computes multiple SHA-256 hashes in a batch
	ComputeBatch(ctx context.Context, in *ComputeBatchRequest, opts ...grpc.CallOption) (*ComputeBatchResponse, error)
	// StreamCompute streams hash computations for high-throughput scenarios
	StreamCompute(ctx context.Context, opts ...grpc.CallOption) (PixieService_StreamComputeClient, error)
	// GetMetrics retrieves performance metrics from eBPF
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// GetDeviceInfo retrieves ASIC device information
	GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error)
}

type pixieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPixieServiceClient(cc grpc.ClientConnInterface) PixieServiceClient {
	return &pixieServiceClient{cc}
}

func (c *pixieServiceClient) ComputeHash(ctx context.Context, in *ComputeHashRequest, opts ...grpc.CallOption) (*ComputeHashResponse, error) {
	out := new(ComputeHashResponse)
	err := c.cc.Invoke(ctx, "/pixie.v1.pixieService/ComputeHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pixieServiceClient) ComputeBatch(ctx context.Context, in *ComputeBatchRequest, opts ...grpc.CallOption) (*ComputeBatchResponse, error) {
	out := new(ComputeBatchResponse)
	err := c.cc.Invoke(ctx, "/pixie.v1.pixieService/ComputeBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pixieServiceClient) StreamCompute(ctx context.Context, opts ...grpc.CallOption) (PixieService_StreamComputeClient, error) {
	stream, err := c.cc.NewStream(ctx, &PixieService_ServiceDesc.Streams[0], "/pixie.v1.pixieService/StreamCompute", opts...)
	if err != nil {
		return nil, err
	}
	x := &pixieServiceStreamComputeClient{stream}
	return x, nil
}

type PixieService_StreamComputeClient interface {
	Send(*StreamComputeRequest) error
	Recv() (*StreamComputeResponse, error)
	grpc.ClientStream
}

type pixieServiceStreamComputeClient struct {
	grpc.ClientStream
}

func (x *pixieServiceStreamComputeClient) Send(m *StreamComputeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pixieServiceStreamComputeClient) Recv() (*StreamComputeResponse, error) {
	m := new(StreamComputeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pixieServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, "/pixie.v1.pixieService/GetMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pixieServiceClient) GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error) {
	out := new(GetDeviceInfoResponse)
	err := c.cc.Invoke(ctx, "/pixie.v1.pixieService/GetDeviceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PixieServiceServer is the server API for PixieService service.
// All implementations must embed UnimplementedPixieServiceServer
// for forward compatibility
type PixieServiceServer interface {
	// ComputeHash computes a single SHA-256 hash
	ComputeHash(context.Context, *ComputeHashRequest) (*ComputeHashResponse, error)
	// ComputeBatch computes multiple SHA-256 hashes in a batch
	ComputeBatch(context.Context, *ComputeBatchRequest) (*ComputeBatchResponse, error)
	// StreamCompute streams hash computations for high-throughput scenarios
	StreamCompute(PixieService_StreamComputeServer) error
	// GetMetrics retrieves performance metrics from eBPF
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	// GetDeviceInfo retrieves ASIC device information
	GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error)
	mustEmbedUnimplementedPixieServiceServer()
}

// UnimplementedPixieServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPixieServiceServer struct {
}

func (UnimplementedPixieServiceServer) ComputeHash(context.Context, *ComputeHashRequest) (*ComputeHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeHash not implemented")
}
func (UnimplementedPixieServiceServer) ComputeBatch(context.Context, *ComputeBatchRequest) (*ComputeBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeBatch not implemented")
}
func (UnimplementedPixieServiceServer) StreamCompute(PixieService_StreamComputeServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamCompute not implemented")
}
func (UnimplementedPixieServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedPixieServiceServer) GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedPixieServiceServer) mustEmbedUnimplementedPixieServiceServer() {}

// UnsafePixieServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PixieServiceServer will
// result in compilation errors.
type UnsafePixieServiceServer interface {
	mustEmbedUnimplementedPixieServiceServer()
}

func RegisterPixieServiceServer(s grpc.ServiceRegistrar, srv PixieServiceServer) {
	s.RegisterService(&PixieService_ServiceDesc, srv)
}

func _PixieService_ComputeHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PixieServiceServer).ComputeHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pixie.v1.pixieService/ComputeHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PixieServiceServer).ComputeHash(ctx, req.(*ComputeHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PixieService_ComputeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PixieServiceServer).ComputeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pixie.v1.pixieService/ComputeBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PixieServiceServer).ComputeBatch(ctx, req.(*ComputeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PixieService_StreamCompute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PixieServiceServer).StreamCompute(&pixieServiceStreamComputeServer{stream})
}

type PixieService_StreamComputeServer interface {
	Send(*StreamComputeResponse) error
	Recv() (*StreamComputeRequest, error)
	grpc.ServerStream
}

type pixieServiceStreamComputeServer struct {
	grpc.ServerStream
}

func (x *pixieServiceStreamComputeServer) Send(m *StreamComputeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pixieServiceStreamComputeServer) Recv() (*StreamComputeRequest, error) {
	m := new(StreamComputeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PixieService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PixieServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pixie.v1.pixieService/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PixieServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PixieService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PixieServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pixie.v1.pixieService/GetDeviceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PixieServiceServer).GetDeviceInfo(ctx, req.(*GetDeviceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PixieService_ServiceDesc is the grpc.ServiceDesc for PixieService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PixieService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pixie.v1.pixieService",
	HandlerType: (*PixieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeHash",
			Handler:    _PixieService_ComputeHash_Handler,
		},
		{
			MethodName: "ComputeBatch",
			Handler:    _PixieService_ComputeBatch_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _PixieService_GetMetrics_Handler,
		},
		{
			MethodName: "GetDeviceInfo",
			Handler:    _PixieService_GetDeviceInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCompute",
			Handler:       _PixieService_StreamCompute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/pixie/v1/pixie.proto",
}
