package teesecurity

import (
	"net"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestNetworkManager_CreateVethPair tests veth pair creation
func TestNetworkManager_CreateVethPair(t *testing.T) {
	// // Skip test if ip command is not available
	// if _, err := exec.LookPath("ip"); err != nil {
	// 	t.Skip("ip command not available, skipping network tests")
	// }

	config := NetworkConfig{
		ContainerIP:    "10.200.0.2/24",
		GatewayIP:      "10.200.0.1",
		EnableInternet: false,
		DNSServers:     []string{"8.8.8.8"},
	}

	mgr := NewNetworkManager(config)

	// Test veth pair creation (this will fail without root, but we can test the logic)
	_, err := mgr.CreateVethPair(12345)
	if err != nil {
		// Expected to fail without root privileges or without proper network namespace
		// Also may fail with "cannot allocate memory" in constrained container environments
		errLower := strings.ToLower(err.Error())
		if !strings.Contains(errLower, "permission denied") &&
			!strings.Contains(errLower, "operation not permitted") &&
			!strings.Contains(err.Error(), "No such process") &&
			!strings.Contains(errLower, "cannot allocate memory") {
			t.Errorf("Unexpected error creating veth pair: %v", err)
		}
	}
}

// TestNetworkManager_ConfigureDNS tests DNS configuration
func TestNetworkManager_ConfigureDNS(t *testing.T) {
	// Test DNS configuration (create a temp file instead of /etc/resolv.conf)
	tempDir := t.TempDir() // Use Go's built-in temp directory creation
	tempFile := filepath.Join(tempDir, "test-resolv.conf")
	config := NetworkConfig{
		DNSServers: []string{"8.8.8.8", "1.1.1.1"},
	}

	// Create the DNS content
	resolvConf := "# Generated by KNIRV-NEXUS\n"
	for _, dns := range config.DNSServers {
		resolvConf += "nameserver " + dns + "\n"
	}

	// Write to temp file
	err := os.WriteFile(tempFile, []byte(resolvConf), 0644)
	if err != nil {
		t.Errorf("Failed to write DNS config: %v", err)
	}

	// Verify content
	content, err := os.ReadFile(tempFile)
	if err != nil {
		t.Errorf("Failed to read DNS config: %v", err)
	}

	expectedContent := "# Generated by KNIRV-NEXUS\nnameserver 8.8.8.8\nnameserver 1.1.1.1\n"
	if string(content) != expectedContent {
		t.Errorf("DNS config content mismatch. Expected:\n%s\nGot:\n%s", expectedContent, string(content))
	}
}

// TestNetworkManager_ParseIP tests IP parsing
func TestNetworkManager_ParseIP(t *testing.T) {
	// Test that the IP parsing doesn't crash
	// (We can't test the actual parsing without root, but we can test the logic)
	containerIP := "10.200.0.2/24"
	_, _, err := net.ParseCIDR(containerIP)
	if err != nil {
		t.Errorf("Failed to parse container IP: %v", err)
	}
}

// TestNetworkManager_DeleteVethPair tests veth pair deletion
func TestNetworkManager_DeleteVethPair(t *testing.T) {
	// // Skip test if ip command is not available
	// if _, err := exec.LookPath("ip"); err != nil {
	// 	t.Skip("ip command not available, skipping network tests")
	// }

	// DeleteVethPair doesn't use any config fields, but we need a NetworkManager
	mgr := NewNetworkManager(NetworkConfig{})

	// Test veth pair deletion (this will fail without root, but we can test the logic)
	vethPair := &VethPair{
		HostInterface:      "nonexistent-veth",
		ContainerInterface: "nonexistent-veth-peer",
	}

	err := mgr.DeleteVethPair(vethPair)
	if err != nil {
		// Expected to fail since the interface doesn't exist
		// Also may fail with "cannot allocate memory" in constrained container environments
		errLower := strings.ToLower(err.Error())
		if !strings.Contains(err.Error(), "cannot find device") &&
			!strings.Contains(err.Error(), "does not exist") &&
			!strings.Contains(err.Error(), "Cannot find device") &&
			!strings.Contains(errLower, "cannot allocate memory") {
			t.Errorf("Unexpected error deleting veth pair: %v", err)
		}
	}
}
