package teesecurity

import (
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
)

// NetworkManager handles network namespace configuration and veth pair setup
type NetworkManager struct {
	config NetworkConfig
}

// NewNetworkManager creates a new NetworkManager instance
func NewNetworkManager(config NetworkConfig) *NetworkManager {
	return &NetworkManager{config: config}
}

// SetupNetworkNamespace configures networking in the container namespace
func (nm *NetworkManager) SetupNetworkNamespace(netnsPath string) error {
	// Basic network setup using ip command
	// This is a simplified version that doesn't require external libraries

	// Bring up loopback interface
	if err := nm.runIPCommand("link", "set", "dev", "lo", "up"); err != nil {
		return fmt.Errorf("failed to bring up loopback: %w", err)
	}

	// Configure veth interface
	if err := nm.configureVethSimple(); err != nil {
		return err
	}

	// Configure DNS
	if err := nm.configureDNS(); err != nil {
		return err
	}

	return nil
}

// configureVethSimple configures the container side of the veth pair using ip command
func (nm *NetworkManager) configureVethSimple() error {
	// Add IP address to container interface
	if err := nm.runIPCommand("addr", "add", nm.config.ContainerIP, "dev", nm.config.ContainerInterface); err != nil {
		return fmt.Errorf("failed to add IP address: %w", err)
	}

	// Bring interface up
	if err := nm.runIPCommand("link", "set", "dev", nm.config.ContainerInterface, "up"); err != nil {
		return fmt.Errorf("failed to bring up interface: %w", err)
	}

	// Add default route if internet enabled
	if nm.config.EnableInternet {
		if err := nm.runIPCommand("route", "add", "default", "via", nm.config.GatewayIP); err != nil {
			return fmt.Errorf("failed to add default route: %w", err)
		}
	}

	return nil
}

// configureDNS sets up DNS resolution
func (nm *NetworkManager) configureDNS() error {
	// Write /etc/resolv.conf
	resolvConf := "# Generated by KNIRV-NEXUS\n"
	for _, dns := range nm.config.DNSServers {
		resolvConf += fmt.Sprintf("nameserver %s\n", dns)
	}

	if err := os.WriteFile("/etc/resolv.conf", []byte(resolvConf), 0644); err != nil {
		return fmt.Errorf("failed to write resolv.conf: %w", err)
	}

	return nil
}

// CreateVethPair creates a veth pair (host side) using ip command
func (nm *NetworkManager) CreateVethPair(containerPID int) (*VethPair, error) {
	hostVeth := fmt.Sprintf("veth-host-%d", containerPID)
	containerVeth := nm.config.ContainerInterface

	// Create veth pair
	if err := nm.runIPCommand("link", "add", hostVeth, "type", "veth", "peer", "name", containerVeth); err != nil {
		return nil, fmt.Errorf("failed to create veth pair: %w", err)
	}

	// Move peer to container namespace
	if err := nm.runIPCommand("link", "set", containerVeth, "netns", strconv.Itoa(containerPID)); err != nil {
		// Cleanup on failure
		nm.runIPCommand("link", "del", hostVeth)
		return nil, fmt.Errorf("failed to move peer to container: %w", err)
	}

	// Configure host side
	gatewayIP := nm.config.GatewayIP
	if err := nm.runIPCommand("addr", "add", fmt.Sprintf("%s/24", gatewayIP), "dev", hostVeth); err != nil {
		return nil, fmt.Errorf("failed to add gateway IP: %w", err)
	}

	if err := nm.runIPCommand("link", "set", hostVeth, "up"); err != nil {
		return nil, fmt.Errorf("failed to bring up host veth: %w", err)
	}

	return &VethPair{
		HostInterface:      hostVeth,
		ContainerInterface: containerVeth,
	}, nil
}

// DeleteVethPair removes the veth pair
func (nm *NetworkManager) DeleteVethPair(vethPair *VethPair) error {
	// Delete veth pair using ip command
	if err := nm.runIPCommand("link", "del", vethPair.HostInterface); err != nil {
		return fmt.Errorf("failed to delete veth pair: %w", err)
	}

	return nil
}

// runIPCommand executes ip command with given arguments
func (nm *NetworkManager) runIPCommand(args ...string) error {
	cmd := exec.Command("ip", args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("ip %s failed: %s: %w", strings.Join(args, " "), string(output), err)
	}
	return nil
}

// strconv.Itoa replacement for container PID
func strconvItoa(i int) string {
	return fmt.Sprintf("%d", i)
}
