#!/bin/bash

# KNIRV Gateway Links Setup Script
# 
# This script sets up the complete gateway links system:
# 1. Makes scripts executable
# 2. Installs required dependencies
# 3. Runs initial configuration
# 4. Deploys gateway services
# 5. Verifies everything is working

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GATEWAY_DIR="$(dirname "$SCRIPT_DIR")"

echo "=== KNIRV Gateway Links Setup ==="
echo "Gateway directory: $GATEWAY_DIR"
echo "Script directory: $SCRIPT_DIR"

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to install npm dependencies if needed
install_dependencies() {
    echo "📦 Checking dependencies..."
    
    # Check if we're in the right directory
    if [ ! -f "$GATEWAY_DIR/package.json" ]; then
        echo "❌ package.json not found in $GATEWAY_DIR"
        exit 1
    fi
    
    cd "$GATEWAY_DIR"
    
    # Install dependencies if node_modules doesn't exist or is empty
    if [ ! -d "node_modules" ] || [ -z "$(ls -A node_modules 2>/dev/null)" ]; then
        echo "📦 Installing npm dependencies..."
        npm install
    else
        echo "✅ Dependencies already installed"
    fi
    
    # Check for required packages
    local required_packages=("js-yaml" "axios" "dotenv")
    local missing_packages=()
    
    for package in "${required_packages[@]}"; do
        if ! npm list "$package" >/dev/null 2>&1; then
            missing_packages+=("$package")
        fi
    done
    
    if [ ${#missing_packages[@]} -gt 0 ]; then
        echo "📦 Installing missing packages: ${missing_packages[*]}"
        npm install "${missing_packages[@]}"
    fi
}

# Function to make scripts executable
make_scripts_executable() {
    echo "🔧 Making scripts executable..."
    
    local scripts=(
        "$SCRIPT_DIR/update-gateway-dns.js"
        "$SCRIPT_DIR/load-gateway-links.js"
        "$SCRIPT_DIR/deploy-gateway-services.js"
        "$SCRIPT_DIR/setup-gateway-links.sh"
    )
    
    for script in "${scripts[@]}"; do
        if [ -f "$script" ]; then
            chmod +x "$script"
            echo "✅ Made executable: $(basename "$script")"
        else
            echo "⚠️  Script not found: $(basename "$script")"
        fi
    done
}

# Function to check environment configuration
check_environment() {
    echo "🔍 Checking environment configuration..."
    
    local env_file="$GATEWAY_DIR/.env.testnet"
    
    if [ ! -f "$env_file" ]; then
        echo "⚠️  .env.testnet file not found"
        echo "   Creating basic configuration..."
        
        cat > "$env_file" << EOF
# KNIRV Gateway Testnet Configuration
# Generated by setup script

# Testnet Mode
TESTNET_MODE=true
NODE_ENV=testnet

# Deployment Mode (will be auto-detected)
DEPLOYMENT_MODE=private_testnet

# CloudFlare DNS configuration (optional - for public testnet)
# CLOUDFLARE_API_TOKEN=your_token_here
# CLOUDFLARE_ZONE_ID=your_zone_id_here

# Gateway Configuration
GATEWAY_PORT=8888
GATEWAY_HOST=localhost

# Service URLs - will be updated by deployment script
PAYMENT_GATEWAY_URL=http://localhost:3001
TUNNEL_REGISTRY_URL=http://localhost:3004
OPERATOR_REGISTRY_URL=http://localhost:3007
WEBGUI_URL=http://localhost:3007

# Last deployment timestamp
LAST_DEPLOYMENT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF
        
        echo "✅ Created basic .env.testnet configuration"
    else
        echo "✅ .env.testnet file exists"
    fi
}

# Function to run initial configuration
run_initial_configuration() {
    echo "⚙️  Running initial configuration..."
    
    cd "$GATEWAY_DIR"
    
    # Load and update gateway links
    echo "📋 Loading gateway links configuration..."
    node "$SCRIPT_DIR/load-gateway-links.js" summary
    
    # Update network website configuration
    echo "🌐 Updating network website configuration..."
    node "$SCRIPT_DIR/load-gateway-links.js" update-website
    
    # Generate JavaScript configuration
    echo "📄 Generating JavaScript configuration..."
    node "$SCRIPT_DIR/load-gateway-links.js" generate-js
    
    echo "✅ Initial configuration completed"
}

# Function to deploy gateway services
deploy_gateway_services() {
    echo "🚀 Deploying gateway services..."
    
    cd "$GATEWAY_DIR"
    
    # Run the deployment script
    node "$SCRIPT_DIR/deploy-gateway-services.js"
    
    echo "✅ Gateway services deployment completed"
}

# Function to verify setup
verify_setup() {
    echo "🔍 Verifying setup..."
    
    local config_files=(
        "$GATEWAY_DIR/config/portal-links.yaml"
        "$GATEWAY_DIR/config/portal-config.json"
        "$GATEWAY_DIR/network-website/public/config/portal-links.yaml"
        "$GATEWAY_DIR/network-website/public/config/portal-config.json"
        "$GATEWAY_DIR/network-website/public/js/gateway-config.js"
        "$GATEWAY_DIR/network-website/public/js/gateway-links.js"
    )
    
    local missing_files=()
    
    for file in "${config_files[@]}"; do
        if [ -f "$file" ]; then
            echo "✅ $(basename "$file")"
        else
            echo "❌ $(basename "$file") - MISSING"
            missing_files+=("$file")
        fi
    done
    
    if [ ${#missing_files[@]} -gt 0 ]; then
        echo "⚠️  Some configuration files are missing:"
        printf '   %s\n' "${missing_files[@]}"
        echo "   This may indicate a setup issue."
    else
        echo "✅ All configuration files present"
    fi
    
    # Check if logs directory exists
    if [ ! -d "$GATEWAY_DIR/logs" ]; then
        mkdir -p "$GATEWAY_DIR/logs"
        echo "✅ Created logs directory"
    fi
}

# Function to display usage information
show_usage() {
    echo "📖 Gateway Links System Usage:"
    echo ""
    echo "Manual Commands:"
    echo "  node scripts/update-gateway-dns.js          - Update DNS records"
    echo "  node scripts/load-gateway-links.js summary  - Show configuration"
    echo "  node scripts/deploy-gateway-services.js     - Full deployment"
    echo ""
    echo "Configuration Files:"
    echo "  config/portal-links.yaml                    - Main configuration"
    echo "  network-website/public/js/gateway-links.js  - Frontend integration"
    echo ""
    echo "Environment:"
    echo "  .env.testnet                                 - Environment configuration"
    echo ""
    echo "For public testnet deployment, add CloudFlare credentials to .env.testnet:"
    echo "  CLOUDFLARE_API_TOKEN=your_token"
    echo "  CLOUDFLARE_ZONE_ID=your_zone_id"
}

# Main execution
main() {
    echo "Starting KNIRV Gateway Links setup..."
    
    # Check prerequisites
    if ! command_exists node; then
        echo "❌ Node.js is required but not installed"
        exit 1
    fi
    
    if ! command_exists npm; then
        echo "❌ npm is required but not installed"
        exit 1
    fi
    
    # Run setup steps
    install_dependencies
    make_scripts_executable
    check_environment
    run_initial_configuration
    deploy_gateway_services
    verify_setup
    
    echo ""
    echo "🎉 KNIRV Gateway Links setup completed successfully!"
    echo ""
    show_usage
}

# Handle command line arguments
case "${1:-}" in
    "help"|"-h"|"--help")
        show_usage
        exit 0
        ;;
    *)
        main "$@"
        ;;
esac
