/**
 * GameLLMService — powers the KNIRVANA tournament loop.
 *
 * Two operations:
 *   propose(challenge, persona)  → agent proposes a solution
 *   evaluate(challenge, proposal) → LLM judge scores 0–1
 *
 * Provider cascade: OpenAI → Gemini → DeepSeek → deterministic mock
 */

import type { Challenge } from '../data/challenges';

// ── Types ─────────────────────────────────────────────────────────────────

export interface AgentPersona {
  id: string;
  name: string;
  systemPrompt: string;
  winRate: number;
  totalEpochs: number;
  wins: number;
}

export interface SolutionProposal {
  chainOfThought: string[];
  solution: string;
  estimatedLatency: number;
}

export interface EvaluationResult {
  score: number;       // 0.0–1.0 composite
  correctness: number; // 0.0–1.0
  efficiency: number;  // 0.0–1.0
  clarity: number;     // 0.0–1.0
  reasoning: string;
}

// ── Default personas ──────────────────────────────────────────────────────

export const DEFAULT_PERSONAS: AgentPersona[] = [
  {
    id: 'persona-debug-specialist',
    name: 'Debug Specialist',
    systemPrompt:
      'You are an expert software debugger. Your strength is finding root causes. ' +
      'When given a buggy code snippet, systematically trace the execution, identify ' +
      'the exact line(s) causing the bug, explain the root cause clearly, and provide ' +
      'a minimal, correct fix. Think step by step.',
    winRate: 0,
    totalEpochs: 0,
    wins: 0,
  },
  {
    id: 'persona-perf-optimizer',
    name: 'Performance Optimizer',
    systemPrompt:
      'You are a performance-focused engineer. When given a buggy code snippet, ' +
      'fix the bug while also optimizing for speed and efficiency. Prefer solutions ' +
      'with better algorithmic complexity. Avoid unnecessary allocations. Explain ' +
      'the performance tradeoffs of your fix.',
    winRate: 0,
    totalEpochs: 0,
    wins: 0,
  },
  {
    id: 'persona-security-analyst',
    name: 'Security Analyst',
    systemPrompt:
      'You are a security-conscious engineer. When given a buggy code snippet, ' +
      'fix the bug with a focus on security implications: input validation, ' +
      'safe defaults, least privilege, and preventing edge-case exploitation. ' +
      'Note any additional security concerns in the existing code.',
    winRate: 0,
    totalEpochs: 0,
    wins: 0,
  },
];

// ── Proposal prompt builder ───────────────────────────────────────────────

function buildProposalPrompt(challenge: Challenge): string {
  return `You are solving a real software bug. Provide your response as JSON only.

## Challenge: ${challenge.title}
**Type:** ${challenge.type}
**Description:** ${challenge.description}
**Expected behavior:** ${challenge.context}

## Buggy Code
\`\`\`typescript
${challenge.buggyCode}
\`\`\`

## Your Task
Fix the bug. Respond with this exact JSON structure:
{
  "chainOfThought": ["step 1 reasoning", "step 2 reasoning", "step 3 reasoning"],
  "solution": "complete corrected code here as a string",
  "confidence": 0.85
}

JSON only. No markdown fences around the JSON.`;
}

// ── Evaluation prompt builder ─────────────────────────────────────────────

function buildEvalPrompt(challenge: Challenge, proposal: SolutionProposal): string {
  return `You are an expert code reviewer. Score a proposed bug fix. Respond with JSON only.

## Original Bug
**Title:** ${challenge.title}
**Type:** ${challenge.type}
**Description:** ${challenge.description}
**Expected behavior:** ${challenge.context}

## Original Buggy Code
\`\`\`typescript
${challenge.buggyCode}
\`\`\`

## Proposed Fix
${proposal.solution}

## Scoring Instructions
Rate each dimension 0.0–1.0:
- correctness: Does the fix actually solve the described bug?
- efficiency: Is the solution reasonably efficient (no unnecessary complexity)?
- clarity: Is the fix readable and well-reasoned?

Respond with this exact JSON:
{
  "correctness": 0.9,
  "efficiency": 0.8,
  "clarity": 0.85,
  "reasoning": "one sentence explaining the score"
}

JSON only. No markdown fences around the JSON.`;
}

// ── Parse helpers ─────────────────────────────────────────────────────────

function parseProposal(raw: string, startMs: number): SolutionProposal {
  try {
    // Strip markdown fences if the model added them anyway
    const cleaned = raw.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    const parsed = JSON.parse(cleaned);
    return {
      chainOfThought: Array.isArray(parsed.chainOfThought)
        ? parsed.chainOfThought
        : ['Solution generated by LLM agent'],
      solution: typeof parsed.solution === 'string' ? parsed.solution : raw,
      estimatedLatency: Date.now() - startMs,
    };
  } catch {
    // Fallback: treat the whole response as the solution
    return {
      chainOfThought: ['LLM agent analyzed the problem and proposed a fix'],
      solution: raw,
      estimatedLatency: Date.now() - startMs,
    };
  }
}

function parseEvaluation(raw: string): EvaluationResult {
  try {
    const cleaned = raw.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    const parsed = JSON.parse(cleaned);
    const correctness = Math.min(1, Math.max(0, Number(parsed.correctness) || 0.5));
    const efficiency  = Math.min(1, Math.max(0, Number(parsed.efficiency)  || 0.5));
    const clarity     = Math.min(1, Math.max(0, Number(parsed.clarity)     || 0.5));
    const score = correctness * 0.6 + efficiency * 0.25 + clarity * 0.15;
    return { score, correctness, efficiency, clarity, reasoning: parsed.reasoning || '' };
  } catch {
    return { score: 0.4, correctness: 0.4, efficiency: 0.4, clarity: 0.4, reasoning: 'Parse error' };
  }
}

// ── Deterministic mock (no API keys) ─────────────────────────────────────

function mockPropose(challenge: Challenge, persona: AgentPersona, startMs: number): SolutionProposal {
  const seed = (persona.id.charCodeAt(0) + challenge.id.charCodeAt(0)) % 10;
  const quality = 0.4 + seed * 0.05; // 0.40–0.85 based on persona+challenge

  const thoughts = [
    `Analyzing ${challenge.type} in: ${challenge.title}`,
    `Root cause identified: ${challenge.description.split('.')[0]}`,
    `Applying ${persona.name} strategy to fix the issue`,
  ];

  const fixComment = `// Fixed by ${persona.name} — ${challenge.type} resolved`;
  const solution = `${fixComment}\n${challenge.buggyCode}\n// TODO: actual fix would be applied here by LLM`;

  return {
    chainOfThought: thoughts,
    solution,
    estimatedLatency: Date.now() - startMs,
  };
}

function mockEvaluate(
  _challenge: Challenge,
  _proposal: SolutionProposal,
  persona: AgentPersona
): EvaluationResult {
  // Deterministic scores so "better" personas win more often in mock mode
  const base = persona.id.includes('debug') ? 0.72
    : persona.id.includes('perf') ? 0.65
    : 0.58;
  const jitter = (Math.random() - 0.5) * 0.2;
  const score = Math.min(1, Math.max(0, base + jitter));
  return {
    score,
    correctness: score + 0.05,
    efficiency: score - 0.05,
    clarity: score,
    reasoning: `Mock evaluation: ${persona.name} scored ${(score * 100).toFixed(0)}%`,
  };
}

// ── Provider implementations ──────────────────────────────────────────────

async function callOpenAI(systemPrompt: string, userPrompt: string): Promise<string> {
  const key = import.meta.env.VITE_OPENAI_API_KEY;
  if (!key) throw new Error('No OpenAI key');

  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${key}`,
    },
    body: JSON.stringify({
      model: 'gpt-4o-mini',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.3,
      max_tokens: 1024,
    }),
  });

  if (!res.ok) throw new Error(`OpenAI ${res.status}`);
  const data = await res.json();
  return data.choices[0]?.message?.content ?? '';
}

async function callGemini(systemPrompt: string, userPrompt: string): Promise<string> {
  const key = import.meta.env.VITE_GOOGLE_API_KEY;
  if (!key) throw new Error('No Gemini key');

  const combinedPrompt = `${systemPrompt}\n\n${userPrompt}`;

  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${key}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: combinedPrompt }] }],
        generationConfig: { temperature: 0.3, maxOutputTokens: 1024 },
      }),
    }
  );

  if (!res.ok) throw new Error(`Gemini ${res.status}`);
  const data = await res.json();
  return data.candidates?.[0]?.content?.parts?.[0]?.text ?? '';
}

async function callDeepSeek(systemPrompt: string, userPrompt: string): Promise<string> {
  const key = import.meta.env.VITE_DEEPSEEK_API_KEY;
  if (!key) throw new Error('No DeepSeek key');

  const res = await fetch('https://api.deepseek.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${key}`,
    },
    body: JSON.stringify({
      model: 'deepseek-chat',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.3,
      max_tokens: 1024,
    }),
  });

  if (!res.ok) throw new Error(`DeepSeek ${res.status}`);
  const data = await res.json();
  return data.choices[0]?.message?.content ?? '';
}

async function callLLM(systemPrompt: string, userPrompt: string): Promise<string> {
  const errors: string[] = [];

  try { return await callOpenAI(systemPrompt, userPrompt); }
  catch (e) { errors.push(`OpenAI: ${(e as Error).message}`); }

  try { return await callGemini(systemPrompt, userPrompt); }
  catch (e) { errors.push(`Gemini: ${(e as Error).message}`); }

  try { return await callDeepSeek(systemPrompt, userPrompt); }
  catch (e) { errors.push(`DeepSeek: ${(e as Error).message}`); }

  throw new Error(`All LLM providers failed: ${errors.join('; ')}`);
}

// ── Public API ────────────────────────────────────────────────────────────

export class GameLLMService {
  private useMock: boolean;

  constructor() {
    // Use mock only if no keys are configured at all
    this.useMock =
      !import.meta.env.VITE_OPENAI_API_KEY &&
      !import.meta.env.VITE_GOOGLE_API_KEY &&
      !import.meta.env.VITE_DEEPSEEK_API_KEY;

    if (this.useMock) {
      console.warn(
        '[GameLLMService] No LLM API keys found. Using deterministic mock. ' +
        'Set VITE_OPENAI_API_KEY, VITE_GOOGLE_API_KEY, or VITE_DEEPSEEK_API_KEY for real gameplay.'
      );
    }
  }

  async propose(challenge: Challenge, persona: AgentPersona): Promise<SolutionProposal> {
    const startMs = Date.now();

    if (this.useMock) {
      // Simulate realistic latency in mock mode
      await new Promise(r => setTimeout(r, 200 + Math.random() * 600));
      return mockPropose(challenge, persona, startMs);
    }

    try {
      const userPrompt = buildProposalPrompt(challenge);
      const raw = await callLLM(persona.systemPrompt, userPrompt);
      return parseProposal(raw, startMs);
    } catch (e) {
      console.error('[GameLLMService] propose failed, using mock:', e);
      return mockPropose(challenge, persona, startMs);
    }
  }

  async evaluate(challenge: Challenge, proposal: SolutionProposal, persona: AgentPersona): Promise<EvaluationResult> {
    if (this.useMock) {
      await new Promise(r => setTimeout(r, 100 + Math.random() * 300));
      return mockEvaluate(challenge, proposal, persona);
    }

    const judgePrompt = 'You are a neutral, expert code reviewer. Evaluate the quality of a bug fix strictly and accurately.';

    try {
      const userPrompt = buildEvalPrompt(challenge, proposal);
      const raw = await callLLM(judgePrompt, userPrompt);
      return parseEvaluation(raw);
    } catch (e) {
      console.error('[GameLLMService] evaluate failed, using mock:', e);
      return mockEvaluate(challenge, proposal, persona);
    }
  }

  isUsingMock(): boolean {
    return this.useMock;
  }
}

// Singleton
let _instance: GameLLMService | null = null;
export function getGameLLMService(): GameLLMService {
  if (!_instance) _instance = new GameLLMService();
  return _instance;
}
