// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.7
// source: internal/proto/hasher/v1/hasher.proto

package hasherv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HasherServiceClient is the client API for HasherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HasherServiceClient interface {
	// ComputeHash computes a single SHA-256 hash
	ComputeHash(ctx context.Context, in *ComputeHashRequest, opts ...grpc.CallOption) (*ComputeHashResponse, error)
	// ComputeBatch computes multiple SHA-256 hashes in a batch
	ComputeBatch(ctx context.Context, in *ComputeBatchRequest, opts ...grpc.CallOption) (*ComputeBatchResponse, error)
	// StreamCompute streams hash computations for high-throughput scenarios
	StreamCompute(ctx context.Context, opts ...grpc.CallOption) (HasherService_StreamComputeClient, error)
	// GetMetrics retrieves performance metrics from eBPF
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// GetDeviceInfo retrieves ASIC device information
	GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error)
}

type hasherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHasherServiceClient(cc grpc.ClientConnInterface) HasherServiceClient {
	return &hasherServiceClient{cc}
}

func (c *hasherServiceClient) ComputeHash(ctx context.Context, in *ComputeHashRequest, opts ...grpc.CallOption) (*ComputeHashResponse, error) {
	out := new(ComputeHashResponse)
	err := c.cc.Invoke(ctx, "/hasher.v1.hasherService/ComputeHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherServiceClient) ComputeBatch(ctx context.Context, in *ComputeBatchRequest, opts ...grpc.CallOption) (*ComputeBatchResponse, error) {
	out := new(ComputeBatchResponse)
	err := c.cc.Invoke(ctx, "/hasher.v1.hasherService/ComputeBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherServiceClient) StreamCompute(ctx context.Context, opts ...grpc.CallOption) (HasherService_StreamComputeClient, error) {
	stream, err := c.cc.NewStream(ctx, &HasherService_ServiceDesc.Streams[0], "/hasher.v1.hasherService/StreamCompute", opts...)
	if err != nil {
		return nil, err
	}
	x := &hasherServiceStreamComputeClient{stream}
	return x, nil
}

type HasherService_StreamComputeClient interface {
	Send(*StreamComputeRequest) error
	Recv() (*StreamComputeResponse, error)
	grpc.ClientStream
}

type hasherServiceStreamComputeClient struct {
	grpc.ClientStream
}

func (x *hasherServiceStreamComputeClient) Send(m *StreamComputeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hasherServiceStreamComputeClient) Recv() (*StreamComputeResponse, error) {
	m := new(StreamComputeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hasherServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, "/hasher.v1.hasherService/GetMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherServiceClient) GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error) {
	out := new(GetDeviceInfoResponse)
	err := c.cc.Invoke(ctx, "/hasher.v1.hasherService/GetDeviceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HasherServiceServer is the server API for HasherService service.
// All implementations must embed UnimplementedHasherServiceServer
// for forward compatibility
type HasherServiceServer interface {
	// ComputeHash computes a single SHA-256 hash
	ComputeHash(context.Context, *ComputeHashRequest) (*ComputeHashResponse, error)
	// ComputeBatch computes multiple SHA-256 hashes in a batch
	ComputeBatch(context.Context, *ComputeBatchRequest) (*ComputeBatchResponse, error)
	// StreamCompute streams hash computations for high-throughput scenarios
	StreamCompute(HasherService_StreamComputeServer) error
	// GetMetrics retrieves performance metrics from eBPF
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	// GetDeviceInfo retrieves ASIC device information
	GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error)
	mustEmbedUnimplementedHasherServiceServer()
}

// UnimplementedHasherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHasherServiceServer struct {
}

func (UnimplementedHasherServiceServer) ComputeHash(context.Context, *ComputeHashRequest) (*ComputeHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeHash not implemented")
}
func (UnimplementedHasherServiceServer) ComputeBatch(context.Context, *ComputeBatchRequest) (*ComputeBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeBatch not implemented")
}
func (UnimplementedHasherServiceServer) StreamCompute(HasherService_StreamComputeServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamCompute not implemented")
}
func (UnimplementedHasherServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedHasherServiceServer) GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedHasherServiceServer) mustEmbedUnimplementedHasherServiceServer() {}

// UnsafeHasherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HasherServiceServer will
// result in compilation errors.
type UnsafeHasherServiceServer interface {
	mustEmbedUnimplementedHasherServiceServer()
}

func RegisterHasherServiceServer(s grpc.ServiceRegistrar, srv HasherServiceServer) {
	s.RegisterService(&HasherService_ServiceDesc, srv)
}

func _HasherService_ComputeHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServiceServer).ComputeHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.v1.hasherService/ComputeHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServiceServer).ComputeHash(ctx, req.(*ComputeHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HasherService_ComputeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServiceServer).ComputeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.v1.hasherService/ComputeBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServiceServer).ComputeBatch(ctx, req.(*ComputeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HasherService_StreamCompute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HasherServiceServer).StreamCompute(&hasherServiceStreamComputeServer{stream})
}

type HasherService_StreamComputeServer interface {
	Send(*StreamComputeResponse) error
	Recv() (*StreamComputeRequest, error)
	grpc.ServerStream
}

type hasherServiceStreamComputeServer struct {
	grpc.ServerStream
}

func (x *hasherServiceStreamComputeServer) Send(m *StreamComputeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hasherServiceStreamComputeServer) Recv() (*StreamComputeRequest, error) {
	m := new(StreamComputeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HasherService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.v1.hasherService/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HasherService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.v1.hasherService/GetDeviceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServiceServer).GetDeviceInfo(ctx, req.(*GetDeviceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HasherService_ServiceDesc is the grpc.ServiceDesc for HasherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HasherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hasher.v1.hasherService",
	HandlerType: (*HasherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeHash",
			Handler:    _HasherService_ComputeHash_Handler,
		},
		{
			MethodName: "ComputeBatch",
			Handler:    _HasherService_ComputeBatch_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _HasherService_GetMetrics_Handler,
		},
		{
			MethodName: "GetDeviceInfo",
			Handler:    _HasherService_GetDeviceInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCompute",
			Handler:       _HasherService_StreamCompute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/hasher/v1/hasher.proto",
}
