// internal/driver/tracer.go
package driver

import (
	"encoding/binary"
	"errors"
	"fmt"
	"sync"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
)

// Event types
const (
	EventComputeStart = 1
	EventComputeEnd   = 2
	EventBatchStart   = 3
	EventBatchEnd     = 4
	EventError        = 5
)

// HashEvent represents an event from eBPF
type HashEvent struct {
	Timestamp uint64
	PID       uint32
	TID       uint32
	EventType uint8
	DataSize  uint32
	LatencyNs uint64
	BatchSize uint32
	Comm      [16]byte
}

// Tracer manages eBPF programs for ASIC monitoring
type Tracer struct {
	objs   *ebpfObjects
	links  []link.Link
	reader *ringbuf.Reader
	events chan HashEvent
	stopCh chan struct{}
	wg     sync.WaitGroup
	mu     sync.Mutex
}

// ebpfObjects holds eBPF maps and programs (auto-generated by bpf2go)
type ebpfObjects struct {
	Programs ebpfPrograms
	Maps     ebpfMaps
}

type ebpfPrograms struct {
	TraceComputeStart *ebpf.Program `ebpf:"trace_compute_start"`
	TraceComputeEnd   *ebpf.Program `ebpf:"trace_compute_end"`
	TraceBatchStart   *ebpf.Program `ebpf:"trace_batch_start"`
	TraceBatchEnd     *ebpf.Program `ebpf:"trace_batch_end"`
}

type ebpfMaps struct {
	ComputeStartTimes *ebpf.Map `ebpf:"compute_start_times"`
	Events            *ebpf.Map `ebpf:"events"`
	Stats             *ebpf.Map `ebpf:"stats"`
}

// HashStats represents statistics from eBPF
type HashStats struct {
	TotalRequests  uint64
	TotalBytes     uint64
	TotalLatencyNs uint64
	PeakLatencyNs  uint64
	ErrorCount     uint64
}

// NewTracer creates a new eBPF tracer
func NewTracer() (*Tracer, error) {
	// In production, this would load the compiled eBPF object
	// For this example, we'll create a mock implementation

	// Load eBPF objects from compiled bytecode
	// objs, err := loadEbpfObjects()
	// if err != nil {
	//     return nil, fmt.Errorf("load eBPF objects: %w", err)
	// }

	// For demonstration, create a minimal tracer
	tracer := &Tracer{
		events: make(chan HashEvent, 1000),
		stopCh: make(chan struct{}),
	}

	// In production, attach uprobes to the Go binary
	// executable, err := os.Executable()
	// if err != nil {
	//     return nil, err
	// }

	// Attach probes to instrumentation points
	// tracer.attachProbes(executable, objs)

	// Start event reader
	// tracer.startEventReader()

	return tracer, nil
}

// attachProbes attaches eBPF uprobes to instrumentation points
func (t *Tracer) attachProbes(executable string, objs *ebpfObjects) error {
	// Open the executable for uprobe attachment
	ex, err := link.OpenExecutable(executable)
	if err != nil {
		return fmt.Errorf("open executable: %w", err)
	}

	// Find symbol offsets in the binary
	symbols := []string{
		"Pixie/internal/driver.pixie_compute_start",
		"Pixie/internal/driver.pixie_compute_end",
		"Pixie/internal/driver.pixie_batch_start",
		"Pixie/internal/driver.pixie_batch_end",
	}

	programs := []*ebpf.Program{
		objs.Programs.TraceComputeStart,
		objs.Programs.TraceComputeEnd,
		objs.Programs.TraceBatchStart,
		objs.Programs.TraceBatchEnd,
	}

	for i, symbol := range symbols {
		// Attach uprobe
		l, err := ex.Uprobe(symbol, programs[i], nil)
		if err != nil {
			return fmt.Errorf("attach uprobe %s: %w", symbol, err)
		}
		t.links = append(t.links, l)
	}

	return nil
}

// startEventReader starts reading events from the ring buffer
func (t *Tracer) startEventReader() error {
	if t.objs == nil {
		return errors.New("eBPF objects not loaded")
	}

	reader, err := ringbuf.NewReader(t.objs.Maps.Events)
	if err != nil {
		return fmt.Errorf("create ring buffer reader: %w", err)
	}
	t.reader = reader

	t.wg.Add(1)
	go func() {
		defer t.wg.Done()
		t.readEvents()
	}()

	return nil
}

// readEvents reads events from the eBPF ring buffer
func (t *Tracer) readEvents() {
	for {
		select {
		case <-t.stopCh:
			return
		default:
			record, err := t.reader.Read()
			if err != nil {
				if errors.Is(err, ringbuf.ErrClosed) {
					return
				}
				continue
			}

			if len(record.RawSample) < int(unsafe.Sizeof(HashEvent{})) {
				continue
			}

			var event HashEvent
			parseEvent(record.RawSample, &event)

			select {
			case t.events <- event:
			default:
				// Buffer full, drop event
			}
		}
	}
}

// GetStats retrieves current statistics from eBPF
func (t *Tracer) GetStats() (*HashStats, error) {
	if t.objs == nil {
		// Return mock stats for demo
		return &HashStats{}, nil
	}

	key := uint32(0)
	var stats HashStats

	err := t.objs.Maps.Stats.Lookup(&key, &stats)
	if err != nil {
		return nil, fmt.Errorf("lookup stats: %w", err)
	}

	return &stats, nil
}

// Events returns the event channel
func (t *Tracer) Events() <-chan HashEvent {
	return t.events
}

// Close closes the tracer and cleans up resources
func (t *Tracer) Close() error {
	close(t.stopCh)

	// Close reader
	if t.reader != nil {
		t.reader.Close()
	}

	// Detach all links
	for _, l := range t.links {
		l.Close()
	}

	// Close eBPF objects
	if t.objs != nil {
		t.objs.Programs.TraceComputeStart.Close()
		t.objs.Programs.TraceComputeEnd.Close()
		t.objs.Programs.TraceBatchStart.Close()
		t.objs.Programs.TraceBatchEnd.Close()
		t.objs.Maps.ComputeStartTimes.Close()
		t.objs.Maps.Events.Close()
		t.objs.Maps.Stats.Close()
	}

	t.wg.Wait()
	close(t.events)

	return nil
}

// Helper function to parse binary event data
func parseEvent(data []byte, event *HashEvent) {
	event.Timestamp = binary.LittleEndian.Uint64(data[0:8])
	event.PID = binary.LittleEndian.Uint32(data[8:12])
	event.TID = binary.LittleEndian.Uint32(data[12:16])
	event.EventType = data[16]
	event.DataSize = binary.LittleEndian.Uint32(data[17:21])
	event.LatencyNs = binary.LittleEndian.Uint64(data[21:29])
	event.BatchSize = binary.LittleEndian.Uint32(data[29:33])
	copy(event.Comm[:], data[33:49])
}

// loadEbpfObjects loads compiled eBPF bytecode
// This would be generated by bpf2go tool:
//
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -type hash_event -type hash_stats ebpf ../../internal/ebpf/pixie.bpf.c -- -I/usr/include/bpf -I.
func loadEbpfObjects() (*ebpfObjects, error) {
	// In production, this loads the compiled .o file
	spec, err := ebpf.LoadCollectionSpec("pixie.bpf.o")
	if err != nil {
		return nil, err
	}

	objs := &ebpfObjects{}
	if err := spec.LoadAndAssign(objs, nil); err != nil {
		return nil, err
	}

	return objs, nil
}
