// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type NexusGuardianGuardianEvent struct {
	Pid       uint32
	Addr      uint32
	Port      uint16
	Comm      [16]int8
	_         [6]byte
	Timestamp uint64
}

// LoadNexusGuardian returns the embedded CollectionSpec for NexusGuardian.
func LoadNexusGuardian() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NexusGuardianBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NexusGuardian: %w", err)
	}

	return spec, err
}

// LoadNexusGuardianObjects loads NexusGuardian and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NexusGuardianObjects
//	*NexusGuardianPrograms
//	*NexusGuardianMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNexusGuardianObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNexusGuardian()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NexusGuardianSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NexusGuardianSpecs struct {
	NexusGuardianProgramSpecs
	NexusGuardianMapSpecs
}

// NexusGuardianSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NexusGuardianProgramSpecs struct {
	TraceConnect *ebpf.ProgramSpec `ebpf:"trace_connect"`
}

// NexusGuardianMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NexusGuardianMapSpecs struct {
	Events            *ebpf.MapSpec `ebpf:"events"`
	GuardianEventType *ebpf.MapSpec `ebpf:"guardian_event_type"`
}

// NexusGuardianObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNexusGuardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type NexusGuardianObjects struct {
	NexusGuardianPrograms
	NexusGuardianMaps
}

func (o *NexusGuardianObjects) Close() error {
	return _NexusGuardianClose(
		&o.NexusGuardianPrograms,
		&o.NexusGuardianMaps,
	)
}

// NexusGuardianMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNexusGuardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type NexusGuardianMaps struct {
	Events            *ebpf.Map `ebpf:"events"`
	GuardianEventType *ebpf.Map `ebpf:"guardian_event_type"`
}

func (m *NexusGuardianMaps) Close() error {
	return _NexusGuardianClose(
		m.Events,
		m.GuardianEventType,
	)
}

// NexusGuardianPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNexusGuardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type NexusGuardianPrograms struct {
	TraceConnect *ebpf.Program `ebpf:"trace_connect"`
}

func (p *NexusGuardianPrograms) Close() error {
	return _NexusGuardianClose(
		p.TraceConnect,
	)
}

func _NexusGuardianClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nexusguardian_bpfel_x86.o
var _NexusGuardianBytes []byte
