// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type telemetryProcessStats struct {
	SyscallCount    [400]uint64
	CpuTimeNs       uint64
	MemoryBytes     uint64
	NetTxBytes      uint64
	NetRxBytes      uint64
	ContextSwitches uint32
	PageFaults      uint32
	ModelName       [64]int8
}

// loadTelemetry returns the embedded CollectionSpec for telemetry.
func loadTelemetry() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TelemetryBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load telemetry: %w", err)
	}

	return spec, err
}

// loadTelemetryObjects loads telemetry and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*telemetryObjects
//	*telemetryPrograms
//	*telemetryMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTelemetryObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTelemetry()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// telemetrySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type telemetrySpecs struct {
	telemetryProgramSpecs
	telemetryMapSpecs
}

// telemetrySpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type telemetryProgramSpecs struct {
	TraceContextSwitch *ebpf.ProgramSpec `ebpf:"trace_context_switch"`
	TracePageAlloc     *ebpf.ProgramSpec `ebpf:"trace_page_alloc"`
}

// telemetryMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type telemetryMapSpecs struct {
	ProcessTelemetry *ebpf.MapSpec `ebpf:"process_telemetry"`
}

// telemetryObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTelemetryObjects or ebpf.CollectionSpec.LoadAndAssign.
type telemetryObjects struct {
	telemetryPrograms
	telemetryMaps
}

func (o *telemetryObjects) Close() error {
	return _TelemetryClose(
		&o.telemetryPrograms,
		&o.telemetryMaps,
	)
}

// telemetryMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTelemetryObjects or ebpf.CollectionSpec.LoadAndAssign.
type telemetryMaps struct {
	ProcessTelemetry *ebpf.Map `ebpf:"process_telemetry"`
}

func (m *telemetryMaps) Close() error {
	return _TelemetryClose(
		m.ProcessTelemetry,
	)
}

// telemetryPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTelemetryObjects or ebpf.CollectionSpec.LoadAndAssign.
type telemetryPrograms struct {
	TraceContextSwitch *ebpf.Program `ebpf:"trace_context_switch"`
	TracePageAlloc     *ebpf.Program `ebpf:"trace_page_alloc"`
}

func (p *telemetryPrograms) Close() error {
	return _TelemetryClose(
		p.TraceContextSwitch,
		p.TracePageAlloc,
	)
}

func _TelemetryClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed telemetry_bpfel_arm64.o
var _TelemetryBytes []byte
