// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type virtualNsVirtualContainer struct {
	ContainerId    uint64
	RootPid        uint32
	Rootfs         [256]int8
	NetworkAllowed uint32
}

// loadVirtualNs returns the embedded CollectionSpec for virtualNs.
func loadVirtualNs() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_VirtualNsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load virtualNs: %w", err)
	}

	return spec, err
}

// loadVirtualNsObjects loads virtualNs and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*virtualNsObjects
//	*virtualNsPrograms
//	*virtualNsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadVirtualNsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadVirtualNs()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// virtualNsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type virtualNsSpecs struct {
	virtualNsProgramSpecs
	virtualNsMapSpecs
}

// virtualNsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type virtualNsProgramSpecs struct {
	VirtualNsFileOpen *ebpf.ProgramSpec `ebpf:"virtual_ns_file_open"`
	VirtualNsNetwork  *ebpf.ProgramSpec `ebpf:"virtual_ns_network"`
}

// virtualNsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type virtualNsMapSpecs struct {
	Containers     *ebpf.MapSpec `ebpf:"containers"`
	PidToContainer *ebpf.MapSpec `ebpf:"pid_to_container"`
}

// virtualNsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadVirtualNsObjects or ebpf.CollectionSpec.LoadAndAssign.
type virtualNsObjects struct {
	virtualNsPrograms
	virtualNsMaps
}

func (o *virtualNsObjects) Close() error {
	return _VirtualNsClose(
		&o.virtualNsPrograms,
		&o.virtualNsMaps,
	)
}

// virtualNsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadVirtualNsObjects or ebpf.CollectionSpec.LoadAndAssign.
type virtualNsMaps struct {
	Containers     *ebpf.Map `ebpf:"containers"`
	PidToContainer *ebpf.Map `ebpf:"pid_to_container"`
}

func (m *virtualNsMaps) Close() error {
	return _VirtualNsClose(
		m.Containers,
		m.PidToContainer,
	)
}

// virtualNsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadVirtualNsObjects or ebpf.CollectionSpec.LoadAndAssign.
type virtualNsPrograms struct {
	VirtualNsFileOpen *ebpf.Program `ebpf:"virtual_ns_file_open"`
	VirtualNsNetwork  *ebpf.Program `ebpf:"virtual_ns_network"`
}

func (p *virtualNsPrograms) Close() error {
	return _VirtualNsClose(
		p.VirtualNsFileOpen,
		p.VirtualNsNetwork,
	)
}

func _VirtualNsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed virtualns_bpfel_x86.o
var _VirtualNsBytes []byte
