package bridge

import (
	"bytes"
	"context"
	"embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	"go.uber.org/zap"
)

// Embed only the build artifact — a single vendored binary, matching
// KNIRVSERVER's own //go:embed bin/backend_server convention. See
// bin/README.md for how the real matrix-construct/tuwunel (Apache-2.0)
// release binary is vendored here before a production build.
//
//go:embed bin/tuwunel
var tuwunelFS embed.FS

// tuwunelPlaceholderMagic marks bin/tuwunel as an unvendored build
// placeholder rather than a real Tuwunel binary.
const tuwunelPlaceholderMagic = "KNIRV_TUWUNEL_PLACEHOLDER_BINARY"

// ErrHomeserverNotVendored is returned by Homeserver.Start when only the
// build-time placeholder is present instead of a real Tuwunel binary. The
// bridge treats this as non-fatal, exactly like this codebase's other
// optional subsystems (TURN, oracle) when their prerequisites are missing:
// the appservice and WhatsApp bridging code still initialize, they simply
// have nothing to talk to yet.
var ErrHomeserverNotVendored = fmt.Errorf("tuwunel binary not vendored (see packages/KNIRVGATEWAY/bin/README.md)")

// Homeserver manages the embedded Tuwunel Matrix homeserver as a
// lifecycle-managed subprocess: a genuine separate process following the
// same embed-extract-exec pattern KNIRVSERVER uses for its own vendored
// binaries, not an in-process library the way the appservice/bridge logic
// itself is.
type Homeserver struct {
	cfg    Config
	logger *zap.Logger

	mu      sync.Mutex
	cmd     *exec.Cmd
	running bool
	waitErr chan error
}

func NewHomeserver(cfg Config, logger *zap.Logger) *Homeserver {
	return &Homeserver{cfg: cfg, logger: logger}
}

// IsVendored reports whether a real Tuwunel binary is available (embedded or
// via cfg.HomeserverBinaryPath) without writing anything to disk — safe to
// call as often as needed, e.g. from the bridge's own status endpoint.
func (h *Homeserver) IsVendored() bool {
	if override := strings.TrimSpace(h.cfg.HomeserverBinaryPath); override != "" {
		_, err := os.Stat(override)
		return err == nil
	}
	data, err := tuwunelFS.ReadFile("bin/tuwunel")
	if err != nil {
		return false
	}
	return len(data) != 0 && !bytes.HasPrefix(bytes.TrimSpace(data), []byte(tuwunelPlaceholderMagic))
}

// extractBinary writes the homeserver binary (embedded, or an operator
// override at cfg.HomeserverBinaryPath) to the runtime data dir and marks it
// executable. Returns ErrHomeserverNotVendored if only the build placeholder
// is available. Only called from Start — never from a read-only path like
// the status endpoint, since it performs a real disk write of a
// potentially large binary every time it runs.
func (h *Homeserver) extractBinary() (string, error) {
	if override := strings.TrimSpace(h.cfg.HomeserverBinaryPath); override != "" {
		if _, err := os.Stat(override); err != nil {
			return "", fmt.Errorf("configured homeserver binary path: %w", err)
		}
		return override, nil
	}

	data, err := tuwunelFS.ReadFile("bin/tuwunel")
	if err != nil {
		return "", fmt.Errorf("read embedded homeserver binary: %w", err)
	}
	if len(data) == 0 || bytes.HasPrefix(bytes.TrimSpace(data), []byte(tuwunelPlaceholderMagic)) {
		return "", ErrHomeserverNotVendored
	}

	dest := h.cfg.homeserverBinaryExtractPath()
	if err := os.MkdirAll(filepath.Dir(dest), 0750); err != nil {
		return "", fmt.Errorf("create homeserver extract dir: %w", err)
	}
	if err := os.WriteFile(dest, data, 0750); err != nil {
		return "", fmt.Errorf("extract homeserver binary: %w", err)
	}
	return dest, nil
}

// writeConfig generates tuwunel.toml. Keys are taken from Tuwunel's own
// documented configuration (server_name, database_path, unix_socket_path,
// appservice_dir, allow_federation, allow_registration) — see
// https://matrix-construct.github.io/tuwunel/configuration.html and
// https://matrix-construct.github.io/tuwunel/appservices.html. This
// deployment is deliberately non-federating and non-self-registering: the
// only consumer is KNIRVGATEWAY's own bridge code (Phase 4's design doc,
// "Why not hand-roll the homeserver too"), never a third-party Matrix
// client or the public Matrix network.
func (h *Homeserver) writeConfig() error {
	if err := os.MkdirAll(h.cfg.homeserverDataDir(), 0750); err != nil {
		return fmt.Errorf("create homeserver data dir: %w", err)
	}
	if err := os.MkdirAll(h.cfg.appservicesDir(), 0750); err != nil {
		return fmt.Errorf("create appservices dir: %w", err)
	}

	cfg := fmt.Sprintf(`# Generated by KNIRVGATEWAY internal/bridge — do not edit by hand.
[global]
server_name = %q
database_path = %q
unix_socket_path = %q
appservice_dir = %q

# Non-federating, non-public: the only client of this homeserver is
# KNIRVGATEWAY's own appservice bridge code, never the public Matrix network
# or a third-party Matrix client.
allow_federation = false
allow_registration = false
allow_guest_registration = false
`,
		h.cfg.HomeserverDomain,
		h.cfg.homeserverDataDir(),
		h.cfg.homeserverClientSocketPath(),
		h.cfg.appservicesDir(),
	)

	return os.WriteFile(h.cfg.homeserverConfigPath(), []byte(cfg), 0600)
}

// Start extracts the homeserver binary, generates its config, and launches
// it as a subprocess. It returns ErrHomeserverNotVendored non-fatally when
// no real binary is available — callers should log and continue rather than
// treat that as a startup failure for the whole bridge.
func (h *Homeserver) Start(ctx context.Context) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.running {
		return nil
	}

	// An unclean previous shutdown (gateway killed with SIGKILL, or crashed)
	// leaves the old Tuwunel process orphaned in its own process group
	// (Setpgid below) rather than reaped. This must happen before
	// extractBinary below: the orphan still has the extracted binary open
	// ("text file busy" on overwrite) and still holds RocksDB's exclusive
	// LOCK file in homeserverDataDir, so a freshly started instance would
	// fail both to extract its binary and to open the database. Reap any
	// such orphan by PID file before doing anything else.
	h.killStaleProcess()

	binPath, err := h.extractBinary()
	if err != nil {
		return err
	}
	if err := h.writeConfig(); err != nil {
		return fmt.Errorf("write homeserver config: %w", err)
	}

	// Stale socket from an unclean previous shutdown would otherwise make a
	// freshly (re)started Tuwunel fail to bind.
	_ = syscall.Unlink(h.cfg.homeserverClientSocketPath())

	cmd := exec.CommandContext(ctx, binPath, "-c", h.cfg.homeserverConfigPath())
	cmd.Env = os.Environ()
	cmd.Stdout = &zapWriter{logger: h.logger, level: "info"}
	cmd.Stderr = &zapWriter{logger: h.logger, level: "warn"}
	// Detach from the gateway's process group so a Ctrl-C to the gateway
	// doesn't race Tuwunel's own SIGTERM handling before Stop() sends it
	// deliberately.
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}

	if err := cmd.Start(); err != nil {
		return fmt.Errorf("start tuwunel: %w", err)
	}

	h.cmd = cmd
	h.running = true
	h.waitErr = make(chan error, 1)
	_ = os.WriteFile(h.pidFilePath(), []byte(strconv.Itoa(cmd.Process.Pid)), 0600)
	go func() {
		h.waitErr <- cmd.Wait()
		_ = os.Remove(h.pidFilePath())
	}()

	h.logger.Info("Tuwunel homeserver started",
		zap.String("binary", binPath),
		zap.String("config", h.cfg.homeserverConfigPath()),
		zap.Int("pid", cmd.Process.Pid))

	return nil
}

func (h *Homeserver) pidFilePath() string {
	return filepath.Join(h.cfg.DataDir, "tuwunel.pid")
}

// killStaleProcess reaps an orphaned Tuwunel process left behind by an
// unclean previous shutdown, identified by pidFilePath. Best-effort: a
// missing or stale PID file, or a PID that's already gone, is not an error —
// it just means there was nothing to clean up.
func (h *Homeserver) killStaleProcess() {
	data, err := os.ReadFile(h.pidFilePath())
	if err != nil {
		return
	}
	pid, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil || pid <= 0 {
		return
	}
	process, err := os.FindProcess(pid)
	if err != nil {
		return
	}
	// On Unix, FindProcess always succeeds; signal 0 is the real liveness
	// check (no-op if alive, ESRCH if not).
	if process.Signal(syscall.Signal(0)) != nil {
		_ = os.Remove(h.pidFilePath())
		return
	}
	h.logger.Warn("Found orphaned Tuwunel process from an unclean previous shutdown — terminating it",
		zap.Int("pid", pid))
	_ = process.Signal(syscall.SIGTERM)
	for i := 0; i < 50; i++ { // up to ~5s
		if process.Signal(syscall.Signal(0)) != nil {
			break
		}
		time.Sleep(100 * time.Millisecond)
	}
	_ = process.Kill()
	_ = os.Remove(h.pidFilePath())
}

// WaitReady polls the homeserver's Client-Server API Unix socket until it
// accepts connections or the timeout elapses. Best-effort: the appservice
// bot client retries its own calls independently, so a timeout here is
// logged, not fatal.
func (h *Homeserver) WaitReady(ctx context.Context, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if fi, err := os.Stat(h.cfg.homeserverClientSocketPath()); err == nil && fi.Mode()&os.ModeSocket != 0 {
			return nil
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(200 * time.Millisecond):
		}
	}
	return fmt.Errorf("timed out waiting for tuwunel to listen on %s", h.cfg.homeserverClientSocketPath())
}

// Stop gracefully terminates the homeserver subprocess.
func (h *Homeserver) Stop(ctx context.Context) error {
	h.mu.Lock()
	cmd := h.cmd
	waitErr := h.waitErr
	running := h.running
	h.running = false
	h.mu.Unlock()

	if !running || cmd == nil || cmd.Process == nil {
		return nil
	}

	_ = cmd.Process.Signal(syscall.SIGTERM)
	select {
	case <-waitErr:
		return nil
	case <-time.After(10 * time.Second):
		_ = cmd.Process.Kill()
		return nil
	case <-ctx.Done():
		_ = cmd.Process.Kill()
		return ctx.Err()
	}
}

// IsRunning reports whether the subprocess is currently managed and alive.
func (h *Homeserver) IsRunning() bool {
	h.mu.Lock()
	defer h.mu.Unlock()
	return h.running
}

// zapWriter adapts a *zap.Logger into an io.Writer for the subprocess's
// stdout/stderr pipes.
type zapWriter struct {
	logger *zap.Logger
	level  string
}

func (w *zapWriter) Write(p []byte) (int, error) {
	line := strings.TrimRight(string(p), "\n")
	if line == "" {
		return len(p), nil
	}
	switch w.level {
	case "warn":
		w.logger.Warn("tuwunel", zap.String("line", line))
	default:
		w.logger.Info("tuwunel", zap.String("line", line))
	}
	return len(p), nil
}
