// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: mcp_descriptors.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for CapabilityType
type CapabilityTypeProto int32

const (
	CapabilityTypeProto_CAPABILITY_TYPE_PROTO_UNSPECIFIED    CapabilityTypeProto = 0
	CapabilityTypeProto_CAPABILITY_TYPE_PROTO_RESOURCE       CapabilityTypeProto = 1
	CapabilityTypeProto_CAPABILITY_TYPE_PROTO_TOOL           CapabilityTypeProto = 2
	CapabilityTypeProto_CAPABILITY_TYPE_PROTO_PROMPT         CapabilityTypeProto = 3
	CapabilityTypeProto_CAPABILITY_TYPE_PROTO_MEMORY_SERVICE CapabilityTypeProto = 4
)

// Enum value maps for CapabilityTypeProto.
var (
	CapabilityTypeProto_name = map[int32]string{
		0: "CAPABILITY_TYPE_PROTO_UNSPECIFIED",
		1: "CAPABILITY_TYPE_PROTO_RESOURCE",
		2: "CAPABILITY_TYPE_PROTO_TOOL",
		3: "CAPABILITY_TYPE_PROTO_PROMPT",
		4: "CAPABILITY_TYPE_PROTO_MEMORY_SERVICE",
	}
	CapabilityTypeProto_value = map[string]int32{
		"CAPABILITY_TYPE_PROTO_UNSPECIFIED":    0,
		"CAPABILITY_TYPE_PROTO_RESOURCE":       1,
		"CAPABILITY_TYPE_PROTO_TOOL":           2,
		"CAPABILITY_TYPE_PROTO_PROMPT":         3,
		"CAPABILITY_TYPE_PROTO_MEMORY_SERVICE": 4,
	}
)

func (x CapabilityTypeProto) Enum() *CapabilityTypeProto {
	p := new(CapabilityTypeProto)
	*p = x
	return p
}

func (x CapabilityTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapabilityTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_descriptors_proto_enumTypes[0].Descriptor()
}

func (CapabilityTypeProto) Type() protoreflect.EnumType {
	return &file_mcp_descriptors_proto_enumTypes[0]
}

func (x CapabilityTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapabilityTypeProto.Descriptor instead.
func (CapabilityTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_mcp_descriptors_proto_rawDescGZIP(), []int{0}
}

// Enum for DiscoveryResourceType (used within ResourceDescriptor)
type DiscoveryResourceTypeProto int32

const (
	DiscoveryResourceTypeProto_DISCOVERY_RESOURCE_TYPE_PROTO_UNSPECIFIED        DiscoveryResourceTypeProto = 0
	DiscoveryResourceTypeProto_DISCOVERY_RESOURCE_TYPE_PROTO_FILE               DiscoveryResourceTypeProto = 1
	DiscoveryResourceTypeProto_DISCOVERY_RESOURCE_TYPE_PROTO_API                DiscoveryResourceTypeProto = 2
	DiscoveryResourceTypeProto_DISCOVERY_RESOURCE_TYPE_PROTO_PLUGIN             DiscoveryResourceTypeProto = 3
	DiscoveryResourceTypeProto_DISCOVERY_RESOURCE_TYPE_PROTO_GENERATED_DOCUMENT DiscoveryResourceTypeProto = 4
	DiscoveryResourceTypeProto_DISCOVERY_RESOURCE_TYPE_PROTO_DATASET            DiscoveryResourceTypeProto = 5
	DiscoveryResourceTypeProto_DISCOVERY_RESOURCE_TYPE_PROTO_MODEL_ARTIFACT     DiscoveryResourceTypeProto = 6
	DiscoveryResourceTypeProto_DISCOVERY_RESOURCE_TYPE_PROTO_SERVICE            DiscoveryResourceTypeProto = 7
)

// Enum value maps for DiscoveryResourceTypeProto.
var (
	DiscoveryResourceTypeProto_name = map[int32]string{
		0: "DISCOVERY_RESOURCE_TYPE_PROTO_UNSPECIFIED",
		1: "DISCOVERY_RESOURCE_TYPE_PROTO_FILE",
		2: "DISCOVERY_RESOURCE_TYPE_PROTO_API",
		3: "DISCOVERY_RESOURCE_TYPE_PROTO_PLUGIN",
		4: "DISCOVERY_RESOURCE_TYPE_PROTO_GENERATED_DOCUMENT",
		5: "DISCOVERY_RESOURCE_TYPE_PROTO_DATASET",
		6: "DISCOVERY_RESOURCE_TYPE_PROTO_MODEL_ARTIFACT",
		7: "DISCOVERY_RESOURCE_TYPE_PROTO_SERVICE",
	}
	DiscoveryResourceTypeProto_value = map[string]int32{
		"DISCOVERY_RESOURCE_TYPE_PROTO_UNSPECIFIED":        0,
		"DISCOVERY_RESOURCE_TYPE_PROTO_FILE":               1,
		"DISCOVERY_RESOURCE_TYPE_PROTO_API":                2,
		"DISCOVERY_RESOURCE_TYPE_PROTO_PLUGIN":             3,
		"DISCOVERY_RESOURCE_TYPE_PROTO_GENERATED_DOCUMENT": 4,
		"DISCOVERY_RESOURCE_TYPE_PROTO_DATASET":            5,
		"DISCOVERY_RESOURCE_TYPE_PROTO_MODEL_ARTIFACT":     6,
		"DISCOVERY_RESOURCE_TYPE_PROTO_SERVICE":            7,
	}
)

func (x DiscoveryResourceTypeProto) Enum() *DiscoveryResourceTypeProto {
	p := new(DiscoveryResourceTypeProto)
	*p = x
	return p
}

func (x DiscoveryResourceTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoveryResourceTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_descriptors_proto_enumTypes[1].Descriptor()
}

func (DiscoveryResourceTypeProto) Type() protoreflect.EnumType {
	return &file_mcp_descriptors_proto_enumTypes[1]
}

func (x DiscoveryResourceTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoveryResourceTypeProto.Descriptor instead.
func (DiscoveryResourceTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_mcp_descriptors_proto_rawDescGZIP(), []int{1}
}

// BaseDescriptorProto corresponds to BaseDescriptor
type BaseDescriptorProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CapabilityType CapabilityTypeProto    `protobuf:"varint,2,opt,name=capability_type,json=capabilityType,proto3,enum=KNIRVORACLE.CapabilityTypeProto" json:"capability_type,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Owner          string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Version        string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	GasFeeNrn      uint64                 `protobuf:"varint,7,opt,name=gas_fee_nrn,json=gasFeeNrn,proto3" json:"gas_fee_nrn,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                 // Using Timestamp for better type safety
	CustomMetadata *structpb.Struct       `protobuf:"bytes,9,opt,name=custom_metadata,json=customMetadata,proto3" json:"custom_metadata,omitempty"` // Maps to map[string]interface{}
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BaseDescriptorProto) Reset() {
	*x = BaseDescriptorProto{}
	mi := &file_mcp_descriptors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseDescriptorProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseDescriptorProto) ProtoMessage() {}

func (x *BaseDescriptorProto) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_descriptors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseDescriptorProto.ProtoReflect.Descriptor instead.
func (*BaseDescriptorProto) Descriptor() ([]byte, []int) {
	return file_mcp_descriptors_proto_rawDescGZIP(), []int{0}
}

func (x *BaseDescriptorProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseDescriptorProto) GetCapabilityType() CapabilityTypeProto {
	if x != nil {
		return x.CapabilityType
	}
	return CapabilityTypeProto_CAPABILITY_TYPE_PROTO_UNSPECIFIED
}

func (x *BaseDescriptorProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseDescriptorProto) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BaseDescriptorProto) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BaseDescriptorProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BaseDescriptorProto) GetGasFeeNrn() uint64 {
	if x != nil {
		return x.GasFeeNrn
	}
	return 0
}

func (x *BaseDescriptorProto) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BaseDescriptorProto) GetCustomMetadata() *structpb.Struct {
	if x != nil {
		return x.CustomMetadata
	}
	return nil
}

// PluginSchemaDetailProto corresponds to PluginSchemaDetail
type PluginSchemaDetailProto struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Summary             string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	AccessInfo          *structpb.Struct       `protobuf:"bytes,2,opt,name=access_info,json=accessInfo,proto3" json:"access_info,omitempty"` // Maps to map[string]interface{}
	LocationHints       []string               `protobuf:"bytes,3,rep,name=location_hints,json=locationHints,proto3" json:"location_hints,omitempty"`
	ManifestFile        string                 `protobuf:"bytes,4,opt,name=manifest_file,json=manifestFile,proto3" json:"manifest_file,omitempty"`
	ExecutableFile      string                 `protobuf:"bytes,5,opt,name=executable_file,json=executableFile,proto3" json:"executable_file,omitempty"`
	OutputDirectoryHint string                 `protobuf:"bytes,6,opt,name=output_directory_hint,json=outputDirectoryHint,proto3" json:"output_directory_hint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PluginSchemaDetailProto) Reset() {
	*x = PluginSchemaDetailProto{}
	mi := &file_mcp_descriptors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSchemaDetailProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSchemaDetailProto) ProtoMessage() {}

func (x *PluginSchemaDetailProto) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_descriptors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSchemaDetailProto.ProtoReflect.Descriptor instead.
func (*PluginSchemaDetailProto) Descriptor() ([]byte, []int) {
	return file_mcp_descriptors_proto_rawDescGZIP(), []int{1}
}

func (x *PluginSchemaDetailProto) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PluginSchemaDetailProto) GetAccessInfo() *structpb.Struct {
	if x != nil {
		return x.AccessInfo
	}
	return nil
}

func (x *PluginSchemaDetailProto) GetLocationHints() []string {
	if x != nil {
		return x.LocationHints
	}
	return nil
}

func (x *PluginSchemaDetailProto) GetManifestFile() string {
	if x != nil {
		return x.ManifestFile
	}
	return ""
}

func (x *PluginSchemaDetailProto) GetExecutableFile() string {
	if x != nil {
		return x.ExecutableFile
	}
	return ""
}

func (x *PluginSchemaDetailProto) GetOutputDirectoryHint() string {
	if x != nil {
		return x.OutputDirectoryHint
	}
	return ""
}

// ResourceDescriptorProto corresponds to ResourceDescriptor
type ResourceDescriptorProto struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	BaseDescriptor *BaseDescriptorProto       `protobuf:"bytes,1,opt,name=base_descriptor,json=baseDescriptor,proto3" json:"base_descriptor,omitempty"`
	ResourceType   DiscoveryResourceTypeProto `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=KNIRVORACLE.DiscoveryResourceTypeProto" json:"resource_type,omitempty"`
	ContentHash    string                     `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Schema         *PluginSchemaDetailProto   `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceDescriptorProto) Reset() {
	*x = ResourceDescriptorProto{}
	mi := &file_mcp_descriptors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptorProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptorProto) ProtoMessage() {}

func (x *ResourceDescriptorProto) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_descriptors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptorProto.ProtoReflect.Descriptor instead.
func (*ResourceDescriptorProto) Descriptor() ([]byte, []int) {
	return file_mcp_descriptors_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceDescriptorProto) GetBaseDescriptor() *BaseDescriptorProto {
	if x != nil {
		return x.BaseDescriptor
	}
	return nil
}

func (x *ResourceDescriptorProto) GetResourceType() DiscoveryResourceTypeProto {
	if x != nil {
		return x.ResourceType
	}
	return DiscoveryResourceTypeProto_DISCOVERY_RESOURCE_TYPE_PROTO_UNSPECIFIED
}

func (x *ResourceDescriptorProto) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *ResourceDescriptorProto) GetSchema() *PluginSchemaDetailProto {
	if x != nil {
		return x.Schema
	}
	return nil
}

// ToolDescriptorProto corresponds to ToolDescriptor
type ToolDescriptorProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BaseDescriptor   *BaseDescriptorProto   `protobuf:"bytes,1,opt,name=base_descriptor,json=baseDescriptor,proto3" json:"base_descriptor,omitempty"`
	InputSchemaJson  string                 `protobuf:"bytes,2,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`    // Keeping as JSON string as schema can be complex
	OutputSchemaJson string                 `protobuf:"bytes,3,opt,name=output_schema_json,json=outputSchemaJson,proto3" json:"output_schema_json,omitempty"` // Keeping as JSON string
	ExecutionPointer string                 `protobuf:"bytes,4,opt,name=execution_pointer,json=executionPointer,proto3" json:"execution_pointer,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolDescriptorProto) Reset() {
	*x = ToolDescriptorProto{}
	mi := &file_mcp_descriptors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDescriptorProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDescriptorProto) ProtoMessage() {}

func (x *ToolDescriptorProto) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_descriptors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDescriptorProto.ProtoReflect.Descriptor instead.
func (*ToolDescriptorProto) Descriptor() ([]byte, []int) {
	return file_mcp_descriptors_proto_rawDescGZIP(), []int{3}
}

func (x *ToolDescriptorProto) GetBaseDescriptor() *BaseDescriptorProto {
	if x != nil {
		return x.BaseDescriptor
	}
	return nil
}

func (x *ToolDescriptorProto) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

func (x *ToolDescriptorProto) GetOutputSchemaJson() string {
	if x != nil {
		return x.OutputSchemaJson
	}
	return ""
}

func (x *ToolDescriptorProto) GetExecutionPointer() string {
	if x != nil {
		return x.ExecutionPointer
	}
	return ""
}

// PromptDescriptorProto corresponds to PromptDescriptor
type PromptDescriptorProto struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BaseDescriptor       *BaseDescriptorProto   `protobuf:"bytes,1,opt,name=base_descriptor,json=baseDescriptor,proto3" json:"base_descriptor,omitempty"`
	Template             string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	ParametersSchemaJson string                 `protobuf:"bytes,3,opt,name=parameters_schema_json,json=parametersSchemaJson,proto3" json:"parameters_schema_json,omitempty"` // Keeping as JSON string
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PromptDescriptorProto) Reset() {
	*x = PromptDescriptorProto{}
	mi := &file_mcp_descriptors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptDescriptorProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptDescriptorProto) ProtoMessage() {}

func (x *PromptDescriptorProto) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_descriptors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptDescriptorProto.ProtoReflect.Descriptor instead.
func (*PromptDescriptorProto) Descriptor() ([]byte, []int) {
	return file_mcp_descriptors_proto_rawDescGZIP(), []int{4}
}

func (x *PromptDescriptorProto) GetBaseDescriptor() *BaseDescriptorProto {
	if x != nil {
		return x.BaseDescriptor
	}
	return nil
}

func (x *PromptDescriptorProto) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *PromptDescriptorProto) GetParametersSchemaJson() string {
	if x != nil {
		return x.ParametersSchemaJson
	}
	return ""
}

// MemoryServiceDescriptorProto corresponds to MemoryServiceDescriptor
type MemoryServiceDescriptorProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BaseDescriptor *BaseDescriptorProto   `protobuf:"bytes,1,opt,name=base_descriptor,json=baseDescriptor,proto3" json:"base_descriptor,omitempty"`
	GraphSchema    string                 `protobuf:"bytes,2,opt,name=graph_schema,json=graphSchema,proto3" json:"graph_schema,omitempty"` // Could be a JSON string or a more structured proto
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryServiceDescriptorProto) Reset() {
	*x = MemoryServiceDescriptorProto{}
	mi := &file_mcp_descriptors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryServiceDescriptorProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryServiceDescriptorProto) ProtoMessage() {}

func (x *MemoryServiceDescriptorProto) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_descriptors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryServiceDescriptorProto.ProtoReflect.Descriptor instead.
func (*MemoryServiceDescriptorProto) Descriptor() ([]byte, []int) {
	return file_mcp_descriptors_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryServiceDescriptorProto) GetBaseDescriptor() *BaseDescriptorProto {
	if x != nil {
		return x.BaseDescriptor
	}
	return nil
}

func (x *MemoryServiceDescriptorProto) GetGraphSchema() string {
	if x != nil {
		return x.GraphSchema
	}
	return ""
}

// Main CapabilityDescriptorProto using oneof
type CapabilityDescriptorContainerProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Descriptor_:
	//
	//	*CapabilityDescriptorContainerProto_Resource
	//	*CapabilityDescriptorContainerProto_Tool
	//	*CapabilityDescriptorContainerProto_Prompt
	//	*CapabilityDescriptorContainerProto_MemoryService
	Descriptor_   isCapabilityDescriptorContainerProto_Descriptor_ `protobuf_oneof:"descriptor"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityDescriptorContainerProto) Reset() {
	*x = CapabilityDescriptorContainerProto{}
	mi := &file_mcp_descriptors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDescriptorContainerProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDescriptorContainerProto) ProtoMessage() {}

func (x *CapabilityDescriptorContainerProto) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_descriptors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDescriptorContainerProto.ProtoReflect.Descriptor instead.
func (*CapabilityDescriptorContainerProto) Descriptor() ([]byte, []int) {
	return file_mcp_descriptors_proto_rawDescGZIP(), []int{6}
}

func (x *CapabilityDescriptorContainerProto) GetDescriptor_() isCapabilityDescriptorContainerProto_Descriptor_ {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *CapabilityDescriptorContainerProto) GetResource() *ResourceDescriptorProto {
	if x != nil {
		if x, ok := x.Descriptor_.(*CapabilityDescriptorContainerProto_Resource); ok {
			return x.Resource
		}
	}
	return nil
}

func (x *CapabilityDescriptorContainerProto) GetTool() *ToolDescriptorProto {
	if x != nil {
		if x, ok := x.Descriptor_.(*CapabilityDescriptorContainerProto_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *CapabilityDescriptorContainerProto) GetPrompt() *PromptDescriptorProto {
	if x != nil {
		if x, ok := x.Descriptor_.(*CapabilityDescriptorContainerProto_Prompt); ok {
			return x.Prompt
		}
	}
	return nil
}

func (x *CapabilityDescriptorContainerProto) GetMemoryService() *MemoryServiceDescriptorProto {
	if x != nil {
		if x, ok := x.Descriptor_.(*CapabilityDescriptorContainerProto_MemoryService); ok {
			return x.MemoryService
		}
	}
	return nil
}

type isCapabilityDescriptorContainerProto_Descriptor_ interface {
	isCapabilityDescriptorContainerProto_Descriptor_()
}

type CapabilityDescriptorContainerProto_Resource struct {
	Resource *ResourceDescriptorProto `protobuf:"bytes,1,opt,name=resource,proto3,oneof"`
}

type CapabilityDescriptorContainerProto_Tool struct {
	Tool *ToolDescriptorProto `protobuf:"bytes,2,opt,name=tool,proto3,oneof"`
}

type CapabilityDescriptorContainerProto_Prompt struct {
	Prompt *PromptDescriptorProto `protobuf:"bytes,3,opt,name=prompt,proto3,oneof"`
}

type CapabilityDescriptorContainerProto_MemoryService struct {
	MemoryService *MemoryServiceDescriptorProto `protobuf:"bytes,4,opt,name=memory_service,json=memoryService,proto3,oneof"`
}

func (*CapabilityDescriptorContainerProto_Resource) isCapabilityDescriptorContainerProto_Descriptor_() {
}

func (*CapabilityDescriptorContainerProto_Tool) isCapabilityDescriptorContainerProto_Descriptor_() {}

func (*CapabilityDescriptorContainerProto_Prompt) isCapabilityDescriptorContainerProto_Descriptor_() {
}

func (*CapabilityDescriptorContainerProto_MemoryService) isCapabilityDescriptorContainerProto_Descriptor_() {
}

// For transaction data
type MCPRegisterCapabilityDataProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId   string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	CapabilityType string                 `protobuf:"bytes,2,opt,name=capability_type,json=capabilityType,proto3" json:"capability_type,omitempty"`
	// bytes descriptor_bytes = 3; // Or use the specific CapabilityDescriptorContainerProto
	CapabilityDescriptor *CapabilityDescriptorContainerProto `protobuf:"bytes,3,opt,name=capability_descriptor,json=capabilityDescriptor,proto3" json:"capability_descriptor,omitempty"` // If you prefer structured proto
	OwnerAddress         string                              `protobuf:"bytes,4,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Fee                  uint64                              `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"` // Add any other fields that are part of this transaction's data
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MCPRegisterCapabilityDataProto) Reset() {
	*x = MCPRegisterCapabilityDataProto{}
	mi := &file_mcp_descriptors_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPRegisterCapabilityDataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPRegisterCapabilityDataProto) ProtoMessage() {}

func (x *MCPRegisterCapabilityDataProto) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_descriptors_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPRegisterCapabilityDataProto.ProtoReflect.Descriptor instead.
func (*MCPRegisterCapabilityDataProto) Descriptor() ([]byte, []int) {
	return file_mcp_descriptors_proto_rawDescGZIP(), []int{7}
}

func (x *MCPRegisterCapabilityDataProto) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *MCPRegisterCapabilityDataProto) GetCapabilityType() string {
	if x != nil {
		return x.CapabilityType
	}
	return ""
}

func (x *MCPRegisterCapabilityDataProto) GetCapabilityDescriptor() *CapabilityDescriptorContainerProto {
	if x != nil {
		return x.CapabilityDescriptor
	}
	return nil
}

func (x *MCPRegisterCapabilityDataProto) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *MCPRegisterCapabilityDataProto) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

// For transaction data update
type MCPUpdateCapabilityDataProto struct {
	state                protoimpl.MessageState              `protogen:"open.v1"`
	CapabilityDescriptor *CapabilityDescriptorContainerProto `protobuf:"bytes,1,opt,name=capability_descriptor,json=capabilityDescriptor,proto3" json:"capability_descriptor,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MCPUpdateCapabilityDataProto) Reset() {
	*x = MCPUpdateCapabilityDataProto{}
	mi := &file_mcp_descriptors_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPUpdateCapabilityDataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPUpdateCapabilityDataProto) ProtoMessage() {}

func (x *MCPUpdateCapabilityDataProto) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_descriptors_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPUpdateCapabilityDataProto.ProtoReflect.Descriptor instead.
func (*MCPUpdateCapabilityDataProto) Descriptor() ([]byte, []int) {
	return file_mcp_descriptors_proto_rawDescGZIP(), []int{8}
}

func (x *MCPUpdateCapabilityDataProto) GetCapabilityDescriptor() *CapabilityDescriptorContainerProto {
	if x != nil {
		return x.CapabilityDescriptor
	}
	return nil
}

var File_mcp_descriptors_proto protoreflect.FileDescriptor

const file_mcp_descriptors_proto_rawDesc = "" +
	"\n" +
	"\x15mcp_descriptors.proto\x12\vKNIRVORACLE\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x02\n" +
	"\x13BaseDescriptorProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12I\n" +
	"\x0fcapability_type\x18\x02 \x01(\x0e2 .KNIRVORACLE.CapabilityTypeProtoR\x0ecapabilityType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1e\n" +
	"\vgas_fee_nrn\x18\a \x01(\x04R\tgasFeeNrn\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12@\n" +
	"\x0fcustom_metadata\x18\t \x01(\v2\x17.google.protobuf.StructR\x0ecustomMetadata\"\x96\x02\n" +
	"\x17PluginSchemaDetailProto\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x128\n" +
	"\vaccess_info\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"accessInfo\x12%\n" +
	"\x0elocation_hints\x18\x03 \x03(\tR\rlocationHints\x12#\n" +
	"\rmanifest_file\x18\x04 \x01(\tR\fmanifestFile\x12'\n" +
	"\x0fexecutable_file\x18\x05 \x01(\tR\x0eexecutableFile\x122\n" +
	"\x15output_directory_hint\x18\x06 \x01(\tR\x13outputDirectoryHint\"\x93\x02\n" +
	"\x17ResourceDescriptorProto\x12I\n" +
	"\x0fbase_descriptor\x18\x01 \x01(\v2 .KNIRVORACLE.BaseDescriptorProtoR\x0ebaseDescriptor\x12L\n" +
	"\rresource_type\x18\x02 \x01(\x0e2'.KNIRVORACLE.DiscoveryResourceTypeProtoR\fresourceType\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\x12<\n" +
	"\x06schema\x18\x04 \x01(\v2$.KNIRVORACLE.PluginSchemaDetailProtoR\x06schema\"\xe7\x01\n" +
	"\x13ToolDescriptorProto\x12I\n" +
	"\x0fbase_descriptor\x18\x01 \x01(\v2 .KNIRVORACLE.BaseDescriptorProtoR\x0ebaseDescriptor\x12*\n" +
	"\x11input_schema_json\x18\x02 \x01(\tR\x0finputSchemaJson\x12,\n" +
	"\x12output_schema_json\x18\x03 \x01(\tR\x10outputSchemaJson\x12+\n" +
	"\x11execution_pointer\x18\x04 \x01(\tR\x10executionPointer\"\xb4\x01\n" +
	"\x15PromptDescriptorProto\x12I\n" +
	"\x0fbase_descriptor\x18\x01 \x01(\v2 .KNIRVORACLE.BaseDescriptorProtoR\x0ebaseDescriptor\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x124\n" +
	"\x16parameters_schema_json\x18\x03 \x01(\tR\x14parametersSchemaJson\"\x8c\x01\n" +
	"\x1cMemoryServiceDescriptorProto\x12I\n" +
	"\x0fbase_descriptor\x18\x01 \x01(\v2 .KNIRVORACLE.BaseDescriptorProtoR\x0ebaseDescriptor\x12!\n" +
	"\fgraph_schema\x18\x02 \x01(\tR\vgraphSchema\"\xc0\x02\n" +
	"\"CapabilityDescriptorContainerProto\x12B\n" +
	"\bresource\x18\x01 \x01(\v2$.KNIRVORACLE.ResourceDescriptorProtoH\x00R\bresource\x126\n" +
	"\x04tool\x18\x02 \x01(\v2 .KNIRVORACLE.ToolDescriptorProtoH\x00R\x04tool\x12<\n" +
	"\x06prompt\x18\x03 \x01(\v2\".KNIRVORACLE.PromptDescriptorProtoH\x00R\x06prompt\x12R\n" +
	"\x0ememory_service\x18\x04 \x01(\v2).KNIRVORACLE.MemoryServiceDescriptorProtoH\x00R\rmemoryServiceB\f\n" +
	"\n" +
	"descriptor\"\x8b\x02\n" +
	"\x1eMCPRegisterCapabilityDataProto\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12'\n" +
	"\x0fcapability_type\x18\x02 \x01(\tR\x0ecapabilityType\x12d\n" +
	"\x15capability_descriptor\x18\x03 \x01(\v2/.KNIRVORACLE.CapabilityDescriptorContainerProtoR\x14capabilityDescriptor\x12#\n" +
	"\rowner_address\x18\x04 \x01(\tR\fownerAddress\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x04R\x03fee\"\x84\x01\n" +
	"\x1cMCPUpdateCapabilityDataProto\x12d\n" +
	"\x15capability_descriptor\x18\x01 \x01(\v2/.KNIRVORACLE.CapabilityDescriptorContainerProtoR\x14capabilityDescriptor*\xcc\x01\n" +
	"\x13CapabilityTypeProto\x12%\n" +
	"!CAPABILITY_TYPE_PROTO_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eCAPABILITY_TYPE_PROTO_RESOURCE\x10\x01\x12\x1e\n" +
	"\x1aCAPABILITY_TYPE_PROTO_TOOL\x10\x02\x12 \n" +
	"\x1cCAPABILITY_TYPE_PROTO_PROMPT\x10\x03\x12(\n" +
	"$CAPABILITY_TYPE_PROTO_MEMORY_SERVICE\x10\x04*\x82\x03\n" +
	"\x1aDiscoveryResourceTypeProto\x12-\n" +
	")DISCOVERY_RESOURCE_TYPE_PROTO_UNSPECIFIED\x10\x00\x12&\n" +
	"\"DISCOVERY_RESOURCE_TYPE_PROTO_FILE\x10\x01\x12%\n" +
	"!DISCOVERY_RESOURCE_TYPE_PROTO_API\x10\x02\x12(\n" +
	"$DISCOVERY_RESOURCE_TYPE_PROTO_PLUGIN\x10\x03\x124\n" +
	"0DISCOVERY_RESOURCE_TYPE_PROTO_GENERATED_DOCUMENT\x10\x04\x12)\n" +
	"%DISCOVERY_RESOURCE_TYPE_PROTO_DATASET\x10\x05\x120\n" +
	",DISCOVERY_RESOURCE_TYPE_PROTO_MODEL_ARTIFACT\x10\x06\x12)\n" +
	"%DISCOVERY_RESOURCE_TYPE_PROTO_SERVICE\x10\aB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_mcp_descriptors_proto_rawDescOnce sync.Once
	file_mcp_descriptors_proto_rawDescData []byte
)

func file_mcp_descriptors_proto_rawDescGZIP() []byte {
	file_mcp_descriptors_proto_rawDescOnce.Do(func() {
		file_mcp_descriptors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_descriptors_proto_rawDesc), len(file_mcp_descriptors_proto_rawDesc)))
	})
	return file_mcp_descriptors_proto_rawDescData
}

var file_mcp_descriptors_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mcp_descriptors_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mcp_descriptors_proto_goTypes = []any{
	(CapabilityTypeProto)(0),                   // 0: KNIRVORACLE.CapabilityTypeProto
	(DiscoveryResourceTypeProto)(0),            // 1: KNIRVORACLE.DiscoveryResourceTypeProto
	(*BaseDescriptorProto)(nil),                // 2: KNIRVORACLE.BaseDescriptorProto
	(*PluginSchemaDetailProto)(nil),            // 3: KNIRVORACLE.PluginSchemaDetailProto
	(*ResourceDescriptorProto)(nil),            // 4: KNIRVORACLE.ResourceDescriptorProto
	(*ToolDescriptorProto)(nil),                // 5: KNIRVORACLE.ToolDescriptorProto
	(*PromptDescriptorProto)(nil),              // 6: KNIRVORACLE.PromptDescriptorProto
	(*MemoryServiceDescriptorProto)(nil),       // 7: KNIRVORACLE.MemoryServiceDescriptorProto
	(*CapabilityDescriptorContainerProto)(nil), // 8: KNIRVORACLE.CapabilityDescriptorContainerProto
	(*MCPRegisterCapabilityDataProto)(nil),     // 9: KNIRVORACLE.MCPRegisterCapabilityDataProto
	(*MCPUpdateCapabilityDataProto)(nil),       // 10: KNIRVORACLE.MCPUpdateCapabilityDataProto
	(*timestamppb.Timestamp)(nil),              // 11: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                    // 12: google.protobuf.Struct
}
var file_mcp_descriptors_proto_depIdxs = []int32{
	0,  // 0: KNIRVORACLE.BaseDescriptorProto.capability_type:type_name -> KNIRVORACLE.CapabilityTypeProto
	11, // 1: KNIRVORACLE.BaseDescriptorProto.timestamp:type_name -> google.protobuf.Timestamp
	12, // 2: KNIRVORACLE.BaseDescriptorProto.custom_metadata:type_name -> google.protobuf.Struct
	12, // 3: KNIRVORACLE.PluginSchemaDetailProto.access_info:type_name -> google.protobuf.Struct
	2,  // 4: KNIRVORACLE.ResourceDescriptorProto.base_descriptor:type_name -> KNIRVORACLE.BaseDescriptorProto
	1,  // 5: KNIRVORACLE.ResourceDescriptorProto.resource_type:type_name -> KNIRVORACLE.DiscoveryResourceTypeProto
	3,  // 6: KNIRVORACLE.ResourceDescriptorProto.schema:type_name -> KNIRVORACLE.PluginSchemaDetailProto
	2,  // 7: KNIRVORACLE.ToolDescriptorProto.base_descriptor:type_name -> KNIRVORACLE.BaseDescriptorProto
	2,  // 8: KNIRVORACLE.PromptDescriptorProto.base_descriptor:type_name -> KNIRVORACLE.BaseDescriptorProto
	2,  // 9: KNIRVORACLE.MemoryServiceDescriptorProto.base_descriptor:type_name -> KNIRVORACLE.BaseDescriptorProto
	4,  // 10: KNIRVORACLE.CapabilityDescriptorContainerProto.resource:type_name -> KNIRVORACLE.ResourceDescriptorProto
	5,  // 11: KNIRVORACLE.CapabilityDescriptorContainerProto.tool:type_name -> KNIRVORACLE.ToolDescriptorProto
	6,  // 12: KNIRVORACLE.CapabilityDescriptorContainerProto.prompt:type_name -> KNIRVORACLE.PromptDescriptorProto
	7,  // 13: KNIRVORACLE.CapabilityDescriptorContainerProto.memory_service:type_name -> KNIRVORACLE.MemoryServiceDescriptorProto
	8,  // 14: KNIRVORACLE.MCPRegisterCapabilityDataProto.capability_descriptor:type_name -> KNIRVORACLE.CapabilityDescriptorContainerProto
	8,  // 15: KNIRVORACLE.MCPUpdateCapabilityDataProto.capability_descriptor:type_name -> KNIRVORACLE.CapabilityDescriptorContainerProto
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_mcp_descriptors_proto_init() }
func file_mcp_descriptors_proto_init() {
	if File_mcp_descriptors_proto != nil {
		return
	}
	file_mcp_descriptors_proto_msgTypes[6].OneofWrappers = []any{
		(*CapabilityDescriptorContainerProto_Resource)(nil),
		(*CapabilityDescriptorContainerProto_Tool)(nil),
		(*CapabilityDescriptorContainerProto_Prompt)(nil),
		(*CapabilityDescriptorContainerProto_MemoryService)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_descriptors_proto_rawDesc), len(file_mcp_descriptors_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_descriptors_proto_goTypes,
		DependencyIndexes: file_mcp_descriptors_proto_depIdxs,
		EnumInfos:         file_mcp_descriptors_proto_enumTypes,
		MessageInfos:      file_mcp_descriptors_proto_msgTypes,
	}.Build()
	File_mcp_descriptors_proto = out.File
	file_mcp_descriptors_proto_goTypes = nil
	file_mcp_descriptors_proto_depIdxs = nil
}
