// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: root_key.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RootKeyFileContentProto struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	StripeSecretKey       string                 `protobuf:"bytes,1,opt,name=stripe_secret_key,json=stripeSecretKey,proto3" json:"stripe_secret_key,omitempty"`
	StripeWebhookSecret   string                 `protobuf:"bytes,2,opt,name=stripe_webhook_secret,json=stripeWebhookSecret,proto3" json:"stripe_webhook_secret,omitempty"`
	CoinbaseApiKey        string                 `protobuf:"bytes,3,opt,name=coinbase_api_key,json=coinbaseApiKey,proto3" json:"coinbase_api_key,omitempty"`
	CoinbaseWebhookSecret string                 `protobuf:"bytes,4,opt,name=coinbase_webhook_secret,json=coinbaseWebhookSecret,proto3" json:"coinbase_webhook_secret,omitempty"`
	RootPrivateKeyHex     string                 `protobuf:"bytes,5,opt,name=root_private_key_hex,json=rootPrivateKeyHex,proto3" json:"root_private_key_hex,omitempty"` // Add any other sensitive root-specific config here
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RootKeyFileContentProto) Reset() {
	*x = RootKeyFileContentProto{}
	mi := &file_root_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootKeyFileContentProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootKeyFileContentProto) ProtoMessage() {}

func (x *RootKeyFileContentProto) ProtoReflect() protoreflect.Message {
	mi := &file_root_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootKeyFileContentProto.ProtoReflect.Descriptor instead.
func (*RootKeyFileContentProto) Descriptor() ([]byte, []int) {
	return file_root_key_proto_rawDescGZIP(), []int{0}
}

func (x *RootKeyFileContentProto) GetStripeSecretKey() string {
	if x != nil {
		return x.StripeSecretKey
	}
	return ""
}

func (x *RootKeyFileContentProto) GetStripeWebhookSecret() string {
	if x != nil {
		return x.StripeWebhookSecret
	}
	return ""
}

func (x *RootKeyFileContentProto) GetCoinbaseApiKey() string {
	if x != nil {
		return x.CoinbaseApiKey
	}
	return ""
}

func (x *RootKeyFileContentProto) GetCoinbaseWebhookSecret() string {
	if x != nil {
		return x.CoinbaseWebhookSecret
	}
	return ""
}

func (x *RootKeyFileContentProto) GetRootPrivateKeyHex() string {
	if x != nil {
		return x.RootPrivateKeyHex
	}
	return ""
}

type EncryptedRootKeyFile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EncryptedContent []byte                 `protobuf:"bytes,1,opt,name=encrypted_content,json=encryptedContent,proto3" json:"encrypted_content,omitempty"`
	Salt             []byte                 `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Nonce            []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EncryptedRootKeyFile) Reset() {
	*x = EncryptedRootKeyFile{}
	mi := &file_root_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedRootKeyFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedRootKeyFile) ProtoMessage() {}

func (x *EncryptedRootKeyFile) ProtoReflect() protoreflect.Message {
	mi := &file_root_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedRootKeyFile.ProtoReflect.Descriptor instead.
func (*EncryptedRootKeyFile) Descriptor() ([]byte, []int) {
	return file_root_key_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedRootKeyFile) GetEncryptedContent() []byte {
	if x != nil {
		return x.EncryptedContent
	}
	return nil
}

func (x *EncryptedRootKeyFile) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *EncryptedRootKeyFile) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

var File_root_key_proto protoreflect.FileDescriptor

const file_root_key_proto_rawDesc = "" +
	"\n" +
	"\x0eroot_key.proto\x12\vKNIRVORACLE\"\x8c\x02\n" +
	"\x17RootKeyFileContentProto\x12*\n" +
	"\x11stripe_secret_key\x18\x01 \x01(\tR\x0fstripeSecretKey\x122\n" +
	"\x15stripe_webhook_secret\x18\x02 \x01(\tR\x13stripeWebhookSecret\x12(\n" +
	"\x10coinbase_api_key\x18\x03 \x01(\tR\x0ecoinbaseApiKey\x126\n" +
	"\x17coinbase_webhook_secret\x18\x04 \x01(\tR\x15coinbaseWebhookSecret\x12/\n" +
	"\x14root_private_key_hex\x18\x05 \x01(\tR\x11rootPrivateKeyHex\"m\n" +
	"\x14EncryptedRootKeyFile\x12+\n" +
	"\x11encrypted_content\x18\x01 \x01(\fR\x10encryptedContent\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\fR\x04salt\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonceB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_root_key_proto_rawDescOnce sync.Once
	file_root_key_proto_rawDescData []byte
)

func file_root_key_proto_rawDescGZIP() []byte {
	file_root_key_proto_rawDescOnce.Do(func() {
		file_root_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_root_key_proto_rawDesc), len(file_root_key_proto_rawDesc)))
	})
	return file_root_key_proto_rawDescData
}

var file_root_key_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_root_key_proto_goTypes = []any{
	(*RootKeyFileContentProto)(nil), // 0: KNIRVORACLE.RootKeyFileContentProto
	(*EncryptedRootKeyFile)(nil),    // 1: KNIRVORACLE.EncryptedRootKeyFile
}
var file_root_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_root_key_proto_init() }
func file_root_key_proto_init() {
	if File_root_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_root_key_proto_rawDesc), len(file_root_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_root_key_proto_goTypes,
		DependencyIndexes: file_root_key_proto_depIdxs,
		MessageInfos:      file_root_key_proto_msgTypes,
	}.Build()
	File_root_key_proto = out.File
	file_root_key_proto_goTypes = nil
	file_root_key_proto_depIdxs = nil
}
