// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type syscallTraceSyscallEvent struct {
	Timestamp uint64
	Pid       uint32
	SyscallId uint32
}

// loadSyscallTrace returns the embedded CollectionSpec for syscallTrace.
func loadSyscallTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SyscallTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load syscallTrace: %w", err)
	}

	return spec, err
}

// loadSyscallTraceObjects loads syscallTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*syscallTraceObjects
//	*syscallTracePrograms
//	*syscallTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSyscallTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSyscallTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// syscallTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscallTraceSpecs struct {
	syscallTraceProgramSpecs
	syscallTraceMapSpecs
}

// syscallTraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscallTraceProgramSpecs struct {
	TraceSysEnter *ebpf.ProgramSpec `ebpf:"trace_sys_enter"`
}

// syscallTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscallTraceMapSpecs struct {
	Events           *ebpf.MapSpec `ebpf:"events"`
	SyscallEventType *ebpf.MapSpec `ebpf:"syscall_event_type"`
}

// syscallTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSyscallTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscallTraceObjects struct {
	syscallTracePrograms
	syscallTraceMaps
}

func (o *syscallTraceObjects) Close() error {
	return _SyscallTraceClose(
		&o.syscallTracePrograms,
		&o.syscallTraceMaps,
	)
}

// syscallTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSyscallTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscallTraceMaps struct {
	Events           *ebpf.Map `ebpf:"events"`
	SyscallEventType *ebpf.Map `ebpf:"syscall_event_type"`
}

func (m *syscallTraceMaps) Close() error {
	return _SyscallTraceClose(
		m.Events,
		m.SyscallEventType,
	)
}

// syscallTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSyscallTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscallTracePrograms struct {
	TraceSysEnter *ebpf.Program `ebpf:"trace_sys_enter"`
}

func (p *syscallTracePrograms) Close() error {
	return _SyscallTraceClose(
		p.TraceSysEnter,
	)
}

func _SyscallTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed syscalltrace_bpfel_x86.o
var _SyscallTraceBytes []byte
