// KNIRVTESTNET GraphChain Explorer Configuration
// Auto-generated by load-endpoints.js
// Environment: staging

window.KNIRV_CONFIG = {
  environment: 'staging',
  apiEndpoints: {
    chain: 'https://testnet.knirv.com/chain',
    graph: 'https://testnet.knirv.com/graph',
    nexus: 'https://testnet.knirv.com/nexus',
    oracle: 'https://testnet.knirv.com/oracle',
    router: 'https://testnet.knirv.com/router',
    knirvana: 'https://testnet.knirv.com/knirvana'
  },
  features: {
    interactiveGraph: true,
    interactiveGraphUrl: 'https://testnet.knirv.com/knirvana-graph',
    testnetMode: true,
    debugMode: true
  }
};