// KNIRVTESTNET GraphChain Explorer Configuration
// Auto-generated by load-endpoints.js
// Environment: testnet

window.KNIRV_CONFIG = {
  environment: 'testnet',
  apiEndpoints: {
    chain: 'http://localhost:8080',
    graph: 'http://localhost:8081',
    nexus: 'http://localhost:8082',
    oracle: 'http://localhost:1317',
    router: 'http://localhost:8086',
    knirvana: 'http://localhost:3000'
  },
  features: {
    interactiveGraph: true,
    interactiveGraphUrl: 'http://localhost:3000',
    testnetMode: true,
    debugMode: true
  }
};