// KNIRVTESTNET GraphChain Explorer Configuration
// Auto-generated by load-endpoints.js
// Environment: testnet

window.KNIRV_CONFIG = {
  environment: 'testnet',
  apiEndpoints: {
    chain: 'https://chain-test.knirv.com',
    graph: 'https://graph-test.knirv.com',
    nexus: 'https://nexus-test.knirv.com',
    oracle: 'https://oracle-test.knirv.com',
    router: 'https://router-test.knirv.com',
    knirvana: 'https://knirvana-test.knirv.com'
  },
  features: {
    interactiveGraph: true,
    interactiveGraphUrl: 'http://localhost:3000',
    testnetMode: true,
    debugMode: true
  }
};