// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package device

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tracerHashStats struct {
	_              structs.HostLayout
	TotalRequests  uint64
	TotalBytes     uint64
	TotalLatencyNs uint64
	PeakLatencyNs  uint64
	ErrorCount     uint64
}

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, err
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
	tracerVariableSpecs
}

// tracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	TraceBatchEnd     *ebpf.ProgramSpec `ebpf:"trace_batch_end"`
	TraceBatchStart   *ebpf.ProgramSpec `ebpf:"trace_batch_start"`
	TraceComputeEnd   *ebpf.ProgramSpec `ebpf:"trace_compute_end"`
	TraceComputeStart *ebpf.ProgramSpec `ebpf:"trace_compute_start"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	ComputeStartTimes *ebpf.MapSpec `ebpf:"compute_start_times"`
	Events            *ebpf.MapSpec `ebpf:"events"`
	Stats             *ebpf.MapSpec `ebpf:"stats"`
}

// tracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerVariableSpecs struct {
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
	tracerVariables
}

func (o *tracerObjects) Close() error {
	return _TracerClose(
		&o.tracerPrograms,
		&o.tracerMaps,
	)
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	ComputeStartTimes *ebpf.Map `ebpf:"compute_start_times"`
	Events            *ebpf.Map `ebpf:"events"`
	Stats             *ebpf.Map `ebpf:"stats"`
}

func (m *tracerMaps) Close() error {
	return _TracerClose(
		m.ComputeStartTimes,
		m.Events,
		m.Stats,
	)
}

// tracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerVariables struct {
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	TraceBatchEnd     *ebpf.Program `ebpf:"trace_batch_end"`
	TraceBatchStart   *ebpf.Program `ebpf:"trace_batch_start"`
	TraceComputeEnd   *ebpf.Program `ebpf:"trace_compute_end"`
	TraceComputeStart *ebpf.Program `ebpf:"trace_compute_start"`
}

func (p *tracerPrograms) Close() error {
	return _TracerClose(
		p.TraceBatchEnd,
		p.TraceBatchStart,
		p.TraceComputeEnd,
		p.TraceComputeStart,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_bpfel.o
var _TracerBytes []byte
