// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { Agent } from './schema/agent.js';
export { Player } from './schema/player.js';
export { Vec3 } from './schema/vec3.js';
