name = "knirv-network"
main = "index.ts"
compatibility_date = "2024-09-09"
assets = { directory = "./public" }

[env.production]
name = "knirv-network-production"
routes = [
  { pattern = "knirv.network/*", custom_domain = true }
]