// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.7
// source: bootnode_key.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootnodeKeyFileContentProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasterWalletKey string `protobuf:"bytes,1,opt,name=master_wallet_key,json=masterWalletKey,proto3" json:"master_wallet_key,omitempty"` // Add any other sensitive bootnode-specific config here
}

func (x *BootnodeKeyFileContentProto) Reset() {
	*x = BootnodeKeyFileContentProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootnode_key_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BootnodeKeyFileContentProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootnodeKeyFileContentProto) ProtoMessage() {}

func (x *BootnodeKeyFileContentProto) ProtoReflect() protoreflect.Message {
	mi := &file_bootnode_key_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootnodeKeyFileContentProto.ProtoReflect.Descriptor instead.
func (*BootnodeKeyFileContentProto) Descriptor() ([]byte, []int) {
	return file_bootnode_key_proto_rawDescGZIP(), []int{0}
}

func (x *BootnodeKeyFileContentProto) GetMasterWalletKey() string {
	if x != nil {
		return x.MasterWalletKey
	}
	return ""
}

type EncryptedBootnodeKeyFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptedContent []byte `protobuf:"bytes,1,opt,name=encrypted_content,json=encryptedContent,proto3" json:"encrypted_content,omitempty"`
	Salt             []byte `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Nonce            []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *EncryptedBootnodeKeyFile) Reset() {
	*x = EncryptedBootnodeKeyFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootnode_key_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptedBootnodeKeyFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedBootnodeKeyFile) ProtoMessage() {}

func (x *EncryptedBootnodeKeyFile) ProtoReflect() protoreflect.Message {
	mi := &file_bootnode_key_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedBootnodeKeyFile.ProtoReflect.Descriptor instead.
func (*EncryptedBootnodeKeyFile) Descriptor() ([]byte, []int) {
	return file_bootnode_key_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedBootnodeKeyFile) GetEncryptedContent() []byte {
	if x != nil {
		return x.EncryptedContent
	}
	return nil
}

func (x *EncryptedBootnodeKeyFile) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *EncryptedBootnodeKeyFile) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

var File_bootnode_key_proto protoreflect.FileDescriptor

var file_bootnode_key_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x6f, 0x6f, 0x74, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x4b, 0x4e, 0x49, 0x52, 0x56, 0x53, 0x45, 0x52, 0x56, 0x45,
	0x52, 0x22, 0x49, 0x0a, 0x1b, 0x42, 0x6f, 0x6f, 0x74, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79,
	0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x71, 0x0a, 0x18,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x74, 0x6e, 0x6f, 0x64,
	0x65, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x65, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_bootnode_key_proto_rawDescOnce sync.Once
	file_bootnode_key_proto_rawDescData = file_bootnode_key_proto_rawDesc
)

func file_bootnode_key_proto_rawDescGZIP() []byte {
	file_bootnode_key_proto_rawDescOnce.Do(func() {
		file_bootnode_key_proto_rawDescData = protoimpl.X.CompressGZIP(file_bootnode_key_proto_rawDescData)
	})
	return file_bootnode_key_proto_rawDescData
}

var file_bootnode_key_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bootnode_key_proto_goTypes = []interface{}{
	(*BootnodeKeyFileContentProto)(nil), // 0: KNIRVSERVER.BootnodeKeyFileContentProto
	(*EncryptedBootnodeKeyFile)(nil),    // 1: KNIRVSERVER.EncryptedBootnodeKeyFile
}
var file_bootnode_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bootnode_key_proto_init() }
func file_bootnode_key_proto_init() {
	if File_bootnode_key_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bootnode_key_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BootnodeKeyFileContentProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootnode_key_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptedBootnodeKeyFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bootnode_key_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bootnode_key_proto_goTypes,
		DependencyIndexes: file_bootnode_key_proto_depIdxs,
		MessageInfos:      file_bootnode_key_proto_msgTypes,
	}.Build()
	File_bootnode_key_proto = out.File
	file_bootnode_key_proto_rawDesc = nil
	file_bootnode_key_proto_goTypes = nil
	file_bootnode_key_proto_depIdxs = nil
}
