// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.7
// source: hasher.proto

package hasher

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HasherServiceClient is the client API for HasherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HasherServiceClient interface {
	ExportSecurityData(ctx context.Context, opts ...grpc.CallOption) (HasherService_ExportSecurityDataClient, error)
	TriggerTraining(ctx context.Context, in *TrainingRequest, opts ...grpc.CallOption) (*TrainingResponse, error)
	GetTrainingStatus(ctx context.Context, in *TrainingStatusRequest, opts ...grpc.CallOption) (*TrainingStatusResponse, error)
	GetUserRules(ctx context.Context, in *RulesRequest, opts ...grpc.CallOption) (*RulesResponse, error)
	ValidateAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
}

type hasherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHasherServiceClient(cc grpc.ClientConnInterface) HasherServiceClient {
	return &hasherServiceClient{cc}
}

func (c *hasherServiceClient) ExportSecurityData(ctx context.Context, opts ...grpc.CallOption) (HasherService_ExportSecurityDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &HasherService_ServiceDesc.Streams[0], "/hasher.HasherService/ExportSecurityData", opts...)
	if err != nil {
		return nil, err
	}
	x := &hasherServiceExportSecurityDataClient{stream}
	return x, nil
}

type HasherService_ExportSecurityDataClient interface {
	Send(*EncryptedChunk) error
	CloseAndRecv() (*ExportResponse, error)
	grpc.ClientStream
}

type hasherServiceExportSecurityDataClient struct {
	grpc.ClientStream
}

func (x *hasherServiceExportSecurityDataClient) Send(m *EncryptedChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hasherServiceExportSecurityDataClient) CloseAndRecv() (*ExportResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ExportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hasherServiceClient) TriggerTraining(ctx context.Context, in *TrainingRequest, opts ...grpc.CallOption) (*TrainingResponse, error) {
	out := new(TrainingResponse)
	err := c.cc.Invoke(ctx, "/hasher.HasherService/TriggerTraining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherServiceClient) GetTrainingStatus(ctx context.Context, in *TrainingStatusRequest, opts ...grpc.CallOption) (*TrainingStatusResponse, error) {
	out := new(TrainingStatusResponse)
	err := c.cc.Invoke(ctx, "/hasher.HasherService/GetTrainingStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherServiceClient) GetUserRules(ctx context.Context, in *RulesRequest, opts ...grpc.CallOption) (*RulesResponse, error) {
	out := new(RulesResponse)
	err := c.cc.Invoke(ctx, "/hasher.HasherService/GetUserRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherServiceClient) ValidateAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, "/hasher.HasherService/ValidateAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HasherServiceServer is the server API for HasherService service.
// All implementations must embed UnimplementedHasherServiceServer
// for forward compatibility
type HasherServiceServer interface {
	ExportSecurityData(HasherService_ExportSecurityDataServer) error
	TriggerTraining(context.Context, *TrainingRequest) (*TrainingResponse, error)
	GetTrainingStatus(context.Context, *TrainingStatusRequest) (*TrainingStatusResponse, error)
	GetUserRules(context.Context, *RulesRequest) (*RulesResponse, error)
	ValidateAction(context.Context, *ActionRequest) (*ActionResponse, error)
	mustEmbedUnimplementedHasherServiceServer()
}

// UnimplementedHasherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHasherServiceServer struct {
}

func (UnimplementedHasherServiceServer) ExportSecurityData(HasherService_ExportSecurityDataServer) error {
	return status.Errorf(codes.Unimplemented, "method ExportSecurityData not implemented")
}
func (UnimplementedHasherServiceServer) TriggerTraining(context.Context, *TrainingRequest) (*TrainingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerTraining not implemented")
}
func (UnimplementedHasherServiceServer) GetTrainingStatus(context.Context, *TrainingStatusRequest) (*TrainingStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrainingStatus not implemented")
}
func (UnimplementedHasherServiceServer) GetUserRules(context.Context, *RulesRequest) (*RulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRules not implemented")
}
func (UnimplementedHasherServiceServer) ValidateAction(context.Context, *ActionRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAction not implemented")
}
func (UnimplementedHasherServiceServer) mustEmbedUnimplementedHasherServiceServer() {}

// UnsafeHasherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HasherServiceServer will
// result in compilation errors.
type UnsafeHasherServiceServer interface {
	mustEmbedUnimplementedHasherServiceServer()
}

func RegisterHasherServiceServer(s grpc.ServiceRegistrar, srv HasherServiceServer) {
	s.RegisterService(&HasherService_ServiceDesc, srv)
}

func _HasherService_ExportSecurityData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HasherServiceServer).ExportSecurityData(&hasherServiceExportSecurityDataServer{stream})
}

type HasherService_ExportSecurityDataServer interface {
	SendAndClose(*ExportResponse) error
	Recv() (*EncryptedChunk, error)
	grpc.ServerStream
}

type hasherServiceExportSecurityDataServer struct {
	grpc.ServerStream
}

func (x *hasherServiceExportSecurityDataServer) SendAndClose(m *ExportResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hasherServiceExportSecurityDataServer) Recv() (*EncryptedChunk, error) {
	m := new(EncryptedChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HasherService_TriggerTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServiceServer).TriggerTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.HasherService/TriggerTraining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServiceServer).TriggerTraining(ctx, req.(*TrainingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HasherService_GetTrainingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServiceServer).GetTrainingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.HasherService/GetTrainingStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServiceServer).GetTrainingStatus(ctx, req.(*TrainingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HasherService_GetUserRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServiceServer).GetUserRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.HasherService/GetUserRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServiceServer).GetUserRules(ctx, req.(*RulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HasherService_ValidateAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServiceServer).ValidateAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.HasherService/ValidateAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServiceServer).ValidateAction(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HasherService_ServiceDesc is the grpc.ServiceDesc for HasherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HasherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hasher.HasherService",
	HandlerType: (*HasherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerTraining",
			Handler:    _HasherService_TriggerTraining_Handler,
		},
		{
			MethodName: "GetTrainingStatus",
			Handler:    _HasherService_GetTrainingStatus_Handler,
		},
		{
			MethodName: "GetUserRules",
			Handler:    _HasherService_GetUserRules_Handler,
		},
		{
			MethodName: "ValidateAction",
			Handler:    _HasherService_ValidateAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportSecurityData",
			Handler:       _HasherService_ExportSecurityData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "hasher.proto",
}
