// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.7
// source: internal/proto/hasher/hasher.proto

package hasher

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HasherTrainingServiceClient is the client API for HasherTrainingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HasherTrainingServiceClient interface {
	ExportSecurityData(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (HasherTrainingService_ExportSecurityDataClient, error)
	TriggerTraining(ctx context.Context, in *TrainingRequest, opts ...grpc.CallOption) (*TrainingResponse, error)
	GetTrainingStatus(ctx context.Context, in *TrainingStatusRequest, opts ...grpc.CallOption) (*TrainingStatusResponse, error)
	GetUserRules(ctx context.Context, in *RulesRequest, opts ...grpc.CallOption) (*RulesResponse, error)
	ValidateAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	StreamActivity(ctx context.Context, in *StreamActivityRequest, opts ...grpc.CallOption) (HasherTrainingService_StreamActivityClient, error)
}

type hasherTrainingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHasherTrainingServiceClient(cc grpc.ClientConnInterface) HasherTrainingServiceClient {
	return &hasherTrainingServiceClient{cc}
}

func (c *hasherTrainingServiceClient) ExportSecurityData(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (HasherTrainingService_ExportSecurityDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &HasherTrainingService_ServiceDesc.Streams[0], "/hasher.HasherTrainingService/ExportSecurityData", opts...)
	if err != nil {
		return nil, err
	}
	x := &hasherTrainingServiceExportSecurityDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HasherTrainingService_ExportSecurityDataClient interface {
	Recv() (*EncryptedChunk, error)
	grpc.ClientStream
}

type hasherTrainingServiceExportSecurityDataClient struct {
	grpc.ClientStream
}

func (x *hasherTrainingServiceExportSecurityDataClient) Recv() (*EncryptedChunk, error) {
	m := new(EncryptedChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hasherTrainingServiceClient) TriggerTraining(ctx context.Context, in *TrainingRequest, opts ...grpc.CallOption) (*TrainingResponse, error) {
	out := new(TrainingResponse)
	err := c.cc.Invoke(ctx, "/hasher.HasherTrainingService/TriggerTraining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherTrainingServiceClient) GetTrainingStatus(ctx context.Context, in *TrainingStatusRequest, opts ...grpc.CallOption) (*TrainingStatusResponse, error) {
	out := new(TrainingStatusResponse)
	err := c.cc.Invoke(ctx, "/hasher.HasherTrainingService/GetTrainingStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherTrainingServiceClient) GetUserRules(ctx context.Context, in *RulesRequest, opts ...grpc.CallOption) (*RulesResponse, error) {
	out := new(RulesResponse)
	err := c.cc.Invoke(ctx, "/hasher.HasherTrainingService/GetUserRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherTrainingServiceClient) ValidateAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, "/hasher.HasherTrainingService/ValidateAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherTrainingServiceClient) StreamActivity(ctx context.Context, in *StreamActivityRequest, opts ...grpc.CallOption) (HasherTrainingService_StreamActivityClient, error) {
	stream, err := c.cc.NewStream(ctx, &HasherTrainingService_ServiceDesc.Streams[1], "/hasher.HasherTrainingService/StreamActivity", opts...)
	if err != nil {
		return nil, err
	}
	x := &hasherTrainingServiceStreamActivityClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HasherTrainingService_StreamActivityClient interface {
	Recv() (*ActivityEvent, error)
	grpc.ClientStream
}

type hasherTrainingServiceStreamActivityClient struct {
	grpc.ClientStream
}

func (x *hasherTrainingServiceStreamActivityClient) Recv() (*ActivityEvent, error) {
	m := new(ActivityEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HasherTrainingServiceServer is the server API for HasherTrainingService service.
// All implementations must embed UnimplementedHasherTrainingServiceServer
// for forward compatibility
type HasherTrainingServiceServer interface {
	ExportSecurityData(*ExportRequest, HasherTrainingService_ExportSecurityDataServer) error
	TriggerTraining(context.Context, *TrainingRequest) (*TrainingResponse, error)
	GetTrainingStatus(context.Context, *TrainingStatusRequest) (*TrainingStatusResponse, error)
	GetUserRules(context.Context, *RulesRequest) (*RulesResponse, error)
	ValidateAction(context.Context, *ActionRequest) (*ActionResponse, error)
	StreamActivity(*StreamActivityRequest, HasherTrainingService_StreamActivityServer) error
	mustEmbedUnimplementedHasherTrainingServiceServer()
}

// UnimplementedHasherTrainingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHasherTrainingServiceServer struct {
}

func (UnimplementedHasherTrainingServiceServer) ExportSecurityData(*ExportRequest, HasherTrainingService_ExportSecurityDataServer) error {
	return status.Errorf(codes.Unimplemented, "method ExportSecurityData not implemented")
}
func (UnimplementedHasherTrainingServiceServer) TriggerTraining(context.Context, *TrainingRequest) (*TrainingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerTraining not implemented")
}
func (UnimplementedHasherTrainingServiceServer) GetTrainingStatus(context.Context, *TrainingStatusRequest) (*TrainingStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrainingStatus not implemented")
}
func (UnimplementedHasherTrainingServiceServer) GetUserRules(context.Context, *RulesRequest) (*RulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRules not implemented")
}
func (UnimplementedHasherTrainingServiceServer) ValidateAction(context.Context, *ActionRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAction not implemented")
}
func (UnimplementedHasherTrainingServiceServer) StreamActivity(*StreamActivityRequest, HasherTrainingService_StreamActivityServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamActivity not implemented")
}
func (UnimplementedHasherTrainingServiceServer) mustEmbedUnimplementedHasherTrainingServiceServer() {}

// UnsafeHasherTrainingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HasherTrainingServiceServer will
// result in compilation errors.
type UnsafeHasherTrainingServiceServer interface {
	mustEmbedUnimplementedHasherTrainingServiceServer()
}

func RegisterHasherTrainingServiceServer(s grpc.ServiceRegistrar, srv HasherTrainingServiceServer) {
	s.RegisterService(&HasherTrainingService_ServiceDesc, srv)
}

func _HasherTrainingService_ExportSecurityData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HasherTrainingServiceServer).ExportSecurityData(m, &hasherTrainingServiceExportSecurityDataServer{stream})
}

type HasherTrainingService_ExportSecurityDataServer interface {
	Send(*EncryptedChunk) error
	grpc.ServerStream
}

type hasherTrainingServiceExportSecurityDataServer struct {
	grpc.ServerStream
}

func (x *hasherTrainingServiceExportSecurityDataServer) Send(m *EncryptedChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _HasherTrainingService_TriggerTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherTrainingServiceServer).TriggerTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.HasherTrainingService/TriggerTraining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherTrainingServiceServer).TriggerTraining(ctx, req.(*TrainingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HasherTrainingService_GetTrainingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherTrainingServiceServer).GetTrainingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.HasherTrainingService/GetTrainingStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherTrainingServiceServer).GetTrainingStatus(ctx, req.(*TrainingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HasherTrainingService_GetUserRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherTrainingServiceServer).GetUserRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.HasherTrainingService/GetUserRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherTrainingServiceServer).GetUserRules(ctx, req.(*RulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HasherTrainingService_ValidateAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherTrainingServiceServer).ValidateAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hasher.HasherTrainingService/ValidateAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherTrainingServiceServer).ValidateAction(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HasherTrainingService_StreamActivity_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamActivityRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HasherTrainingServiceServer).StreamActivity(m, &hasherTrainingServiceStreamActivityServer{stream})
}

type HasherTrainingService_StreamActivityServer interface {
	Send(*ActivityEvent) error
	grpc.ServerStream
}

type hasherTrainingServiceStreamActivityServer struct {
	grpc.ServerStream
}

func (x *hasherTrainingServiceStreamActivityServer) Send(m *ActivityEvent) error {
	return x.ServerStream.SendMsg(m)
}

// HasherTrainingService_ServiceDesc is the grpc.ServiceDesc for HasherTrainingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HasherTrainingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hasher.HasherTrainingService",
	HandlerType: (*HasherTrainingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerTraining",
			Handler:    _HasherTrainingService_TriggerTraining_Handler,
		},
		{
			MethodName: "GetTrainingStatus",
			Handler:    _HasherTrainingService_GetTrainingStatus_Handler,
		},
		{
			MethodName: "GetUserRules",
			Handler:    _HasherTrainingService_GetUserRules_Handler,
		},
		{
			MethodName: "ValidateAction",
			Handler:    _HasherTrainingService_ValidateAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportSecurityData",
			Handler:       _HasherTrainingService_ExportSecurityData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamActivity",
			Handler:       _HasherTrainingService_StreamActivity_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/hasher/hasher.proto",
}
