// Copyright 2026 KNIRV-SERVER
// SPDX-License-Identifier: GPL-3.0-or-later

// Package wasm provides the Badge-to-WASM mapping service that links DVE
// Badge ontology tags to pre-compiled .wasm modules generated by KNIRVHASHER.
//
// This implements Step 1 of the WASM Integration Investigation:
//
//	Map "Guardrail" tags in Badges to rules.wasm.
//	Map "Resolution/Recovery" tags in Badges to resolution.wasm.
//
// WASM binaries are produced by the KNIRVHASHER transformer pipeline
// (packages/KNIRVHASHER/pkg/hashing/transformer/compiler.go) and stored
// in a configurable output directory (default /var/heart/wasm/).  Each
// .wasm file is named by its SHA-256 hash.
//
// Badge-to-tag-to-WASM mapping is persisted so that subsequent guardrail
// evaluations and eBPF-triggered resolutions can look up the correct
// WASM module without re-scanning the directory.
package wasm

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// WASMType classifies the kind of WASM module (matching KNIRVHASHER types).
type WASMType string

const (
	WASMTypeRule       WASMType = "rule"
	WASMTypeResolution WASMType = "resolution"
	WASMTypePatch      WASMType = "patch"
)

// WASMExport names expected on compiled WASM modules (per Investigation §2.1).
const (
	ExportGuardrailClass = "GuardrailClass" // rules.wasm → uint32
	ExportResolveError   = "resolveError"   // resolution.wasm → bool
	ExportErrorClass     = "ErrorClass"     // resolution.wasm → uint32
)

// BadgeTagClassification groups ontology tags by their WASM role.
type BadgeTagClassification string

const (
	TagClassGuardrail  BadgeTagClassification = "guardrail"
	TagClassResolution BadgeTagClassification = "resolution"
	TagClassPatch      BadgeTagClassification = "patch"
	TagClassUnknown    BadgeTagClassification = "unknown"
)

// WASMMapping links one Badge ontology tag to a specific .wasm file on disk.
type WASMMapping struct {
	BadgeID  string   `json:"badge_id"`
	Tag      string   `json:"tag"`
	WASMType WASMType `json:"wasm_type"`
	WASMPath string   `json:"wasm_path"`
	WASMHash string   `json:"wasm_hash"`
}

// BadgeEntry tracks all WASM mappings for a single Badge NFT.
type BadgeEntry struct {
	BadgeID  string        `json:"badge_id"`
	Mappings []WASMMapping `json:"mappings"`
}

// BadgeWASMMapper is the core Badge-to-WASM mapping service.  It:
//   - Scans the KNIRVHASHER WASM output directory for compiled modules.
//   - Maps Badge ontology tags to their corresponding .wasm files.
//   - Provides a lookup for the WazeroGate runtime and middleware.
type BadgeWASMMapper struct {
	wasmDir    string
	entries    map[string]*BadgeEntry // badgeID → BadgeEntry
	mu         sync.RWMutex
	persistPath string // optional path for JSON persistence
}

// NewBadgeWASMMapper creates a mapper that reads .wasm modules from wasmDir.
// If persistPath is non-empty the mapping table is saved/loaded as JSON.
func NewBadgeWASMMapper(wasmDir, persistPath string) *BadgeWASMMapper {
	m := &BadgeWASMMapper{
		wasmDir:     wasmDir,
		entries:     make(map[string]*BadgeEntry),
		persistPath: persistPath,
	}
	if persistPath != "" {
		m.loadPersisted()
	}
	return m
}

// DefaultWASMDir returns the default KNIRVHASHER WASM output directory.
func DefaultWASMDir() string {
	if d := os.Getenv("KNIRV_WASM_OUT_DIR"); d != "" {
		return d
	}
	if _, err := os.Stat("/var/heart/wasm"); err == nil {
		return "/var/heart/wasm"
	}
	return "/var/lib/knirvserver/wasm"
}

// RegisterBadge scans the WASM directory for modules matching the given
// Badge ontology tags and builds the mapping table.  Each tag is classified
// as guardrail, resolution, or patch, and linked to the appropriate .wasm.
func (m *BadgeWASMMapper) RegisterBadge(badgeID string, ontologyTags []string) error {
	if badgeID == "" {
		return fmt.Errorf("badge ID is required")
	}

	m.mu.Lock()
	defer m.mu.Unlock()

	entry := &BadgeEntry{BadgeID: badgeID}

	for _, tag := range ontologyTags {
		tag = strings.TrimSpace(tag)
		if tag == "" {
			continue
		}

		class := classifyTag(tag)
		wasmType := classToWASMType(class)

		// Try to find a matching .wasm for this tag.
		wasmPath, wasmHash := m.findWASMForTag(tag, wasmType)

		mapping := WASMMapping{
			BadgeID:  badgeID,
			Tag:      tag,
			WASMType: wasmType,
			WASMPath: wasmPath,
			WASMHash: wasmHash,
		}
		entry.Mappings = append(entry.Mappings, mapping)

		if wasmPath != "" {
			log.Printf("[wasm-mapper] badge=%s tag=%s class=%s → %s (%s)",
				badgeID, tag, class, filepath.Base(wasmPath), wasmType)
		} else {
			log.Printf("[wasm-mapper] badge=%s tag=%s class=%s → no WASM found yet",
				badgeID, tag, class)
		}
	}

	m.entries[badgeID] = entry
	if m.persistPath != "" {
		m.savePersisted()
	}
	return nil
}

// RemoveBadge removes all mappings for a badge (e.g. when DVE decommissioned).
func (m *BadgeWASMMapper) RemoveBadge(badgeID string) {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.entries, badgeID)
	if m.persistPath != "" {
		m.savePersisted()
	}
}

// GetGuardrailWASM returns the .wasm paths for all "guardrail" tags on a badge.
func (m *BadgeWASMMapper) GetGuardrailWASM(badgeID string) []WASMMapping {
	return m.getByClassification(badgeID, TagClassGuardrail)
}

// GetResolutionWASM returns the .wasm paths for all "resolution" tags on a badge.
func (m *BadgeWASMMapper) GetResolutionWASM(badgeID string) []WASMMapping {
	return m.getByClassification(badgeID, TagClassResolution)
}

// GetPatchWASM returns the .wasm paths for all "patch" tags on a badge.
func (m *BadgeWASMMapper) GetPatchWASM(badgeID string) []WASMMapping {
	return m.getByClassification(badgeID, TagClassPatch)
}

// LookupWASM finds the WASM mapping for a specific badge+tag combination.
// Returns the .wasm path, WASMType, and error if not found.
func (m *BadgeWASMMapper) LookupWASM(badgeID, tag string) (string, WASMType, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()

	entry, ok := m.entries[badgeID]
	if !ok {
		return "", "", fmt.Errorf("badge %s not registered", badgeID)
	}
	for _, mp := range entry.Mappings {
		if strings.EqualFold(mp.Tag, tag) {
			if mp.WASMPath == "" {
				return "", mp.WASMType, fmt.Errorf("no WASM module for tag %s on badge %s", tag, badgeID)
			}
			return mp.WASMPath, mp.WASMType, nil
		}
	}
	return "", "", fmt.Errorf("tag %s not found on badge %s", tag, badgeID)
}

// GetEntry returns the full BadgeEntry for a badge.
func (m *BadgeWASMMapper) GetEntry(badgeID string) (*BadgeEntry, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	e, ok := m.entries[badgeID]
	return e, ok
}

// ListBadges returns all registered badge IDs.
func (m *BadgeWASMMapper) ListBadges() []string {
	m.mu.RLock()
	defer m.mu.RUnlock()
	ids := make([]string, 0, len(m.entries))
	for id := range m.entries {
		ids = append(ids, id)
	}
	return ids
}

// RefreshWASMDir re-scans the WASM directory and updates all paths for
// existing badge mappings.  Call this after KNIRVHASHER generates new WASM.
func (m *BadgeWASMMapper) RefreshWASMDir() {
	m.mu.Lock()
	defer m.mu.Unlock()

	for _, entry := range m.entries {
		for i := range entry.Mappings {
			mp := &entry.Mappings[i]
			wasmPath, wasmHash := m.findWASMForTag(mp.Tag, mp.WASMType)
			if wasmPath != "" {
				mp.WASMPath = wasmPath
				mp.WASMHash = wasmHash
			}
		}
	}
	if m.persistPath != "" {
		m.savePersisted()
	}
	log.Printf("[wasm-mapper] refreshed %d badge entries", len(m.entries))
}

// Stats returns mapper statistics.
func (m *BadgeWASMMapper) Stats() map[string]interface{} {
	m.mu.RLock()
	defer m.mu.RUnlock()

	totalBadges := len(m.entries)
	withGuardrail := 0
	withResolution := 0
	withPatch := 0

	for _, entry := range m.entries {
		for _, mp := range entry.Mappings {
			if mp.WASMPath == "" {
				continue
			}
			switch classifyTag(mp.Tag) {
			case TagClassGuardrail:
				withGuardrail++
			case TagClassResolution:
				withResolution++
			case TagClassPatch:
				withPatch++
			}
		}
	}

	return map[string]interface{}{
		"total_badges":       totalBadges,
		"guardrail_wasm":     withGuardrail,
		"resolution_wasm":    withResolution,
		"patch_wasm":         withPatch,
		"wasm_dir":           m.wasmDir,
	}
}

// —— internal helpers ——

func (m *BadgeWASMMapper) getByClassification(badgeID string, class BadgeTagClassification) []WASMMapping {
	m.mu.RLock()
	defer m.mu.RUnlock()

	entry, ok := m.entries[badgeID]
	if !ok {
		return nil
	}
	var result []WASMMapping
	for _, mp := range entry.Mappings {
		if classifyTag(mp.Tag) == class && mp.WASMPath != "" {
			result = append(result, mp)
		}
	}
	return result
}

// findWASMForTag scans the WASM directory for a .wasm file whose SHA-256
// filename or embedded metadata matches the given tag and type.
func (m *BadgeWASMMapper) findWASMForTag(tag string, wasmType WASMType) (path, hash string) {
	if m.wasmDir == "" {
		return "", ""
	}

	entries, err := os.ReadDir(m.wasmDir)
	if err != nil {
		return "", ""
	}

	// Phase 1: look for files named by type prefix (e.g. "rule_*.wasm")
	// These are the intermediate names before final hash rename.
	typePrefix := string(wasmType) + "_"
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".wasm") {
			continue
		}
		if strings.HasPrefix(e.Name(), typePrefix) {
			fp := filepath.Join(m.wasmDir, e.Name())
			h, err := fileHash(fp)
			if err == nil {
				return fp, h
			}
		}
	}

	// Phase 2: look for hash-named files (sha256hex.wasm).
	// We can't match by tag directly from filename, but if there's only one
	// file of the expected type, return it.
	var candidates []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".wasm") {
			continue
		}
		// Hash-named: 64 hex chars + ".wasm"
		base := strings.TrimSuffix(e.Name(), ".wasm")
		if len(base) == 64 && isHex(base) {
			candidates = append(candidates, e.Name())
		}
	}

	// If we've got candidates, return the most recent by mod time.
	if len(candidates) > 0 {
		var newest string
		var newestTime int64
		for _, c := range candidates {
			fp := filepath.Join(m.wasmDir, c)
			info, err := os.Stat(fp)
			if err != nil {
				continue
			}
			if info.ModTime().Unix() > newestTime {
				newestTime = info.ModTime().Unix()
				newest = fp
			}
		}
		if newest != "" {
			h, err := fileHash(newest)
			if err == nil {
				return newest, h
			}
		}
	}

	return "", ""
}

// —— persistence ——

func (m *BadgeWASMMapper) savePersisted() {
	if m.persistPath == "" {
		return
	}
	data, err := json.MarshalIndent(m.entries, "", "  ")
	if err != nil {
		log.Printf("[wasm-mapper] persist marshal error: %v", err)
		return
	}
	if err := os.WriteFile(m.persistPath, data, 0644); err != nil {
		log.Printf("[wasm-mapper] persist write error: %v", err)
	}
}

func (m *BadgeWASMMapper) loadPersisted() {
	data, err := os.ReadFile(m.persistPath)
	if err != nil {
		return
	}
	var entries map[string]*BadgeEntry
	if err := json.Unmarshal(data, &entries); err != nil {
		log.Printf("[wasm-mapper] persist parse error: %v", err)
		return
	}
	m.entries = entries
	log.Printf("[wasm-mapper] loaded %d badge entries from %s", len(entries), m.persistPath)
}

// —— tag classification ——

// classifyTag determines whether an ontology tag maps to guardrail,
// resolution, or patch WASM.
func classifyTag(tag string) BadgeTagClassification {
	lower := strings.ToLower(tag)

	// Guardrail / policy / rule tags
	guardrailPatterns := []string{
		"guardrail", "guard", "policy", "rule", "compliance",
		"audit", "sandbox", "lsm", "seccomp",
		"ontology:guard", "ontology:policy",
	}
	for _, p := range guardrailPatterns {
		if strings.Contains(lower, p) {
			return TagClassGuardrail
		}
	}

	// Resolution / recovery / error tags
	resolutionPatterns := []string{
		"resolution", "resolve", "recovery", "error", "remediation",
		"heal", "self-heal", "restart", "rollback",
		"ontology:resolve", "ontology:error",
	}
	for _, p := range resolutionPatterns {
		if strings.Contains(lower, p) {
			return TagClassResolution
		}
	}

	// Patch / update tags
	patchPatterns := []string{
		"patch", "update", "hotfix", "migrate",
	}
	for _, p := range patchPatterns {
		if strings.Contains(lower, p) {
			return TagClassPatch
		}
	}

	return TagClassUnknown
}

func classToWASMType(class BadgeTagClassification) WASMType {
	switch class {
	case TagClassGuardrail:
		return WASMTypeRule
	case TagClassResolution:
		return WASMTypeResolution
	case TagClassPatch:
		return WASMTypePatch
	default:
		return WASMTypeRule
	}
}

// —— utility ——

func fileHash(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	h := sha256.Sum256(data)
	return hex.EncodeToString(h[:]), nil
}

func isHex(s string) bool {
	if s == "" {
		return false
	}
	for _, c := range s {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')) {
			return false
		}
	}
	return true
}
