name = "knirv-com"
main = "index.ts"
compatibility_date = "2024-09-09"
assets = { directory = "./public" }

[env.production]
name = "knirv-com-production"
routes = [
  { pattern = "knirv.com/*", custom_domain = true }
]