// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: proto/bootnode_key.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootnodeKeyFileContentProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MasterWalletKey string                 `protobuf:"bytes,1,opt,name=master_wallet_key,json=masterWalletKey,proto3" json:"master_wallet_key,omitempty"` // Add any other sensitive bootnode-specific config here
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BootnodeKeyFileContentProto) Reset() {
	*x = BootnodeKeyFileContentProto{}
	mi := &file_proto_bootnode_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootnodeKeyFileContentProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootnodeKeyFileContentProto) ProtoMessage() {}

func (x *BootnodeKeyFileContentProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootnode_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootnodeKeyFileContentProto.ProtoReflect.Descriptor instead.
func (*BootnodeKeyFileContentProto) Descriptor() ([]byte, []int) {
	return file_proto_bootnode_key_proto_rawDescGZIP(), []int{0}
}

func (x *BootnodeKeyFileContentProto) GetMasterWalletKey() string {
	if x != nil {
		return x.MasterWalletKey
	}
	return ""
}

type EncryptedBootnodeKeyFile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EncryptedContent []byte                 `protobuf:"bytes,1,opt,name=encrypted_content,json=encryptedContent,proto3" json:"encrypted_content,omitempty"`
	Salt             []byte                 `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Nonce            []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EncryptedBootnodeKeyFile) Reset() {
	*x = EncryptedBootnodeKeyFile{}
	mi := &file_proto_bootnode_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedBootnodeKeyFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedBootnodeKeyFile) ProtoMessage() {}

func (x *EncryptedBootnodeKeyFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootnode_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedBootnodeKeyFile.ProtoReflect.Descriptor instead.
func (*EncryptedBootnodeKeyFile) Descriptor() ([]byte, []int) {
	return file_proto_bootnode_key_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedBootnodeKeyFile) GetEncryptedContent() []byte {
	if x != nil {
		return x.EncryptedContent
	}
	return nil
}

func (x *EncryptedBootnodeKeyFile) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *EncryptedBootnodeKeyFile) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

var File_proto_bootnode_key_proto protoreflect.FileDescriptor

const file_proto_bootnode_key_proto_rawDesc = "" +
	"\n" +
	"\x18proto/bootnode_key.proto\x12\n" +
	"KNIRVROOT\"I\n" +
	"\x1bBootnodeKeyFileContentProto\x12*\n" +
	"\x11master_wallet_key\x18\x01 \x01(\tR\x0fmasterWalletKey\"q\n" +
	"\x18EncryptedBootnodeKeyFile\x12+\n" +
	"\x11encrypted_content\x18\x01 \x01(\fR\x10encryptedContent\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\fR\x04salt\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonceB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_bootnode_key_proto_rawDescOnce sync.Once
	file_proto_bootnode_key_proto_rawDescData []byte
)

func file_proto_bootnode_key_proto_rawDescGZIP() []byte {
	file_proto_bootnode_key_proto_rawDescOnce.Do(func() {
		file_proto_bootnode_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bootnode_key_proto_rawDesc), len(file_proto_bootnode_key_proto_rawDesc)))
	})
	return file_proto_bootnode_key_proto_rawDescData
}

var file_proto_bootnode_key_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bootnode_key_proto_goTypes = []any{
	(*BootnodeKeyFileContentProto)(nil), // 0: KNIRVROOT.BootnodeKeyFileContentProto
	(*EncryptedBootnodeKeyFile)(nil),    // 1: KNIRVROOT.EncryptedBootnodeKeyFile
}
var file_proto_bootnode_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bootnode_key_proto_init() }
func file_proto_bootnode_key_proto_init() {
	if File_proto_bootnode_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bootnode_key_proto_rawDesc), len(file_proto_bootnode_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bootnode_key_proto_goTypes,
		DependencyIndexes: file_proto_bootnode_key_proto_depIdxs,
		MessageInfos:      file_proto_bootnode_key_proto_msgTypes,
	}.Build()
	File_proto_bootnode_key_proto = out.File
	file_proto_bootnode_key_proto_goTypes = nil
	file_proto_bootnode_key_proto_depIdxs = nil
}
