// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: proto/hashing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionProto defines the structure of a transaction for hashing.
// Fields like signature and public_key are part of the full transaction
// but are excluded from the data that is hashed for the signature itself.
type TransactionProto struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	From      string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To        string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Value     uint64                 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Data      []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // Can hold serialized MCP data or other arbitrary data
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Fee       uint64                 `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	Type      string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"` // For MCP transaction types
	// TransactionHash is derived, and PublicKey/Signature are added after hashing for signing.
	// For hashing the core content to be signed, these are excluded from the hash calculation.
	Signature     []byte `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                  // Cryptographic signature of the transaction
	PublicKey     []byte `protobuf:"bytes,9,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Public key of the signer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionProto) Reset() {
	*x = TransactionProto{}
	mi := &file_proto_hashing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionProto) ProtoMessage() {}

func (x *TransactionProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hashing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionProto.ProtoReflect.Descriptor instead.
func (*TransactionProto) Descriptor() ([]byte, []int) {
	return file_proto_hashing_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionProto) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransactionProto) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransactionProto) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TransactionProto) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TransactionProto) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TransactionProto) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TransactionProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransactionProto) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TransactionProto) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// BlockProto defines the structure of a block for hashing.
// The BlockHash itself is derived from this structure and not included here.
type BlockProto struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber  uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	PrevHash     []byte                 `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Timestamp    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce        int32                  `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"` // Assuming Block.Nonce is int, maps to int32
	Transactions []*TransactionProto    `protobuf:"bytes,5,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// SmartContract field is removed.
	ProposerAddress string `protobuf:"bytes,6,opt,name=proposer_address,json=proposerAddress,proto3" json:"proposer_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockProto) Reset() {
	*x = BlockProto{}
	mi := &file_proto_hashing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockProto) ProtoMessage() {}

func (x *BlockProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hashing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockProto.ProtoReflect.Descriptor instead.
func (*BlockProto) Descriptor() ([]byte, []int) {
	return file_proto_hashing_proto_rawDescGZIP(), []int{1}
}

func (x *BlockProto) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BlockProto) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *BlockProto) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BlockProto) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *BlockProto) GetTransactions() []*TransactionProto {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BlockProto) GetProposerAddress() string {
	if x != nil {
		return x.ProposerAddress
	}
	return ""
}

var File_proto_hashing_proto protoreflect.FileDescriptor

const file_proto_hashing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/hashing.proto\x12\tKNIRVROOT\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n" +
	"\x10TransactionProto\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x04R\x05value\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x04R\x03fee\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\t \x01(\fR\tpublicKey\"\x88\x02\n" +
	"\n" +
	"BlockProto\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tprev_hash\x18\x02 \x01(\fR\bprevHash\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x05R\x05nonce\x12?\n" +
	"\ftransactions\x18\x05 \x03(\v2\x1b.KNIRVROOT.TransactionProtoR\ftransactions\x12)\n" +
	"\x10proposer_address\x18\x06 \x01(\tR\x0fproposerAddressB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_hashing_proto_rawDescOnce sync.Once
	file_proto_hashing_proto_rawDescData []byte
)

func file_proto_hashing_proto_rawDescGZIP() []byte {
	file_proto_hashing_proto_rawDescOnce.Do(func() {
		file_proto_hashing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hashing_proto_rawDesc), len(file_proto_hashing_proto_rawDesc)))
	})
	return file_proto_hashing_proto_rawDescData
}

var file_proto_hashing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_hashing_proto_goTypes = []any{
	(*TransactionProto)(nil),      // 0: KNIRVROOT.TransactionProto
	(*BlockProto)(nil),            // 1: KNIRVROOT.BlockProto
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_hashing_proto_depIdxs = []int32{
	2, // 0: KNIRVROOT.TransactionProto.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: KNIRVROOT.BlockProto.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: KNIRVROOT.BlockProto.transactions:type_name -> KNIRVROOT.TransactionProto
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_hashing_proto_init() }
func file_proto_hashing_proto_init() {
	if File_proto_hashing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hashing_proto_rawDesc), len(file_proto_hashing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_hashing_proto_goTypes,
		DependencyIndexes: file_proto_hashing_proto_depIdxs,
		MessageInfos:      file_proto_hashing_proto_msgTypes,
	}.Build()
	File_proto_hashing_proto = out.File
	file_proto_hashing_proto_goTypes = nil
	file_proto_hashing_proto_depIdxs = nil
}
