// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type sandboxLsmSandboxPolicy struct {
	AllowedPrefix  [256]int8
	NetworkAllowed uint32
}

// loadSandboxLsm returns the embedded CollectionSpec for sandboxLsm.
func loadSandboxLsm() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SandboxLsmBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sandboxLsm: %w", err)
	}

	return spec, err
}

// loadSandboxLsmObjects loads sandboxLsm and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sandboxLsmObjects
//	*sandboxLsmPrograms
//	*sandboxLsmMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSandboxLsmObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSandboxLsm()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sandboxLsmSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sandboxLsmSpecs struct {
	sandboxLsmProgramSpecs
	sandboxLsmMapSpecs
}

// sandboxLsmSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sandboxLsmProgramSpecs struct {
	RestrictFileOpen *ebpf.ProgramSpec `ebpf:"restrict_file_open"`
	RestrictNetwork  *ebpf.ProgramSpec `ebpf:"restrict_network"`
}

// sandboxLsmMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sandboxLsmMapSpecs struct {
	Policies *ebpf.MapSpec `ebpf:"policies"`
}

// sandboxLsmObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSandboxLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type sandboxLsmObjects struct {
	sandboxLsmPrograms
	sandboxLsmMaps
}

func (o *sandboxLsmObjects) Close() error {
	return _SandboxLsmClose(
		&o.sandboxLsmPrograms,
		&o.sandboxLsmMaps,
	)
}

// sandboxLsmMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSandboxLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type sandboxLsmMaps struct {
	Policies *ebpf.Map `ebpf:"policies"`
}

func (m *sandboxLsmMaps) Close() error {
	return _SandboxLsmClose(
		m.Policies,
	)
}

// sandboxLsmPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSandboxLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type sandboxLsmPrograms struct {
	RestrictFileOpen *ebpf.Program `ebpf:"restrict_file_open"`
	RestrictNetwork  *ebpf.Program `ebpf:"restrict_network"`
}

func (p *sandboxLsmPrograms) Close() error {
	return _SandboxLsmClose(
		p.RestrictFileOpen,
		p.RestrictNetwork,
	)
}

func _SandboxLsmClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sandboxlsm_bpfel_arm64.o
var _SandboxLsmBytes []byte
