// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type xdpFilterRateLimit struct {
	Packets     uint64
	Bytes       uint64
	WindowStart uint64
	Dropped     uint64
}

// loadXdpFilter returns the embedded CollectionSpec for xdpFilter.
func loadXdpFilter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpFilterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdpFilter: %w", err)
	}

	return spec, err
}

// loadXdpFilterObjects loads xdpFilter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpFilterObjects
//	*xdpFilterPrograms
//	*xdpFilterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpFilterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdpFilter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpFilterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpFilterSpecs struct {
	xdpFilterProgramSpecs
	xdpFilterMapSpecs
}

// xdpFilterSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpFilterProgramSpecs struct {
	XdpRateLimit *ebpf.ProgramSpec `ebpf:"xdp_rate_limit"`
}

// xdpFilterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpFilterMapSpecs struct {
	RateLimits *ebpf.MapSpec `ebpf:"rate_limits"`
	Whitelist  *ebpf.MapSpec `ebpf:"whitelist"`
}

// xdpFilterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpFilterObjects struct {
	xdpFilterPrograms
	xdpFilterMaps
}

func (o *xdpFilterObjects) Close() error {
	return _XdpFilterClose(
		&o.xdpFilterPrograms,
		&o.xdpFilterMaps,
	)
}

// xdpFilterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpFilterMaps struct {
	RateLimits *ebpf.Map `ebpf:"rate_limits"`
	Whitelist  *ebpf.Map `ebpf:"whitelist"`
}

func (m *xdpFilterMaps) Close() error {
	return _XdpFilterClose(
		m.RateLimits,
		m.Whitelist,
	)
}

// xdpFilterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpFilterPrograms struct {
	XdpRateLimit *ebpf.Program `ebpf:"xdp_rate_limit"`
}

func (p *xdpFilterPrograms) Close() error {
	return _XdpFilterClose(
		p.XdpRateLimit,
	)
}

func _XdpFilterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpfilter_bpfel_arm64.o
var _XdpFilterBytes []byte
